//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 16-4-2010 12:08:37
namespace MagentoImport
{
    
    /// <summary>
    /// There are no comments for MagContContainer in the schema.
    /// </summary>
    public partial class MagContContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MagContContainer object using the connection string found in the 'MagContContainer' section of the application configuration file.
        /// </summary>
        public MagContContainer() : 
                base("name=MagContContainer", "MagContContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MagContContainer object.
        /// </summary>
        public MagContContainer(string connectionString) : 
                base(connectionString, "MagContContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MagContContainer object.
        /// </summary>
        public MagContContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MagContContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
    }
}
