//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concentrator.Web.ServiceClient.SelectorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://Concentrator.selectorservice.nl/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://Concentrator.selectorservice.nl/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Concentrator.selectorservice.nl/", ConfigurationName="SelectorService.SelectorServiceSoap")]
    public interface SelectorServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetSelectorsResult from namespace http://Concentrator.selectorservice.nl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.selectorservice.nl/GetSelectors", ReplyAction="*")]
        Concentrator.Web.ServiceClient.SelectorService.GetSelectorsResponse GetSelectors(Concentrator.Web.ServiceClient.SelectorService.GetSelectorsRequest request);
        
        // CODEGEN: Generating message contract since element name query from namespace http://Concentrator.selectorservice.nl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.selectorservice.nl/FindProduct", ReplyAction="*")]
        Concentrator.Web.ServiceClient.SelectorService.FindProductResponse FindProduct(Concentrator.Web.ServiceClient.SelectorService.FindProductRequest request);
        
        // CODEGEN: Generating message contract since element name vendorItemNumber from namespace http://Concentrator.selectorservice.nl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.selectorservice.nl/FindCompatibleProducts", ReplyAction="*")]
        Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsResponse FindCompatibleProducts(Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllSelectorProductsResult from namespace http://Concentrator.selectorservice.nl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.selectorservice.nl/GetAllSelectorProducts", ReplyAction="*")]
        Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsResponse GetAllSelectorProducts(Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsRequest request);
        
        // CODEGEN: Generating message contract since element name ExportSelectorsResult from namespace http://Concentrator.selectorservice.nl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.selectorservice.nl/ExportSelectors", ReplyAction="*")]
        Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsResponse ExportSelectors(Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSelectorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSelectors", Namespace="http://Concentrator.selectorservice.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.GetSelectorsRequestBody Body;
        
        public GetSelectorsRequest() {
        }
        
        public GetSelectorsRequest(Concentrator.Web.ServiceClient.SelectorService.GetSelectorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSelectorsRequestBody {
        
        public GetSelectorsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSelectorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSelectorsResponse", Namespace="http://Concentrator.selectorservice.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.GetSelectorsResponseBody Body;
        
        public GetSelectorsResponse() {
        }
        
        public GetSelectorsResponse(Concentrator.Web.ServiceClient.SelectorService.GetSelectorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Concentrator.selectorservice.nl/")]
    public partial class GetSelectorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.ArrayOfInt GetSelectorsResult;
        
        public GetSelectorsResponseBody() {
        }
        
        public GetSelectorsResponseBody(Concentrator.Web.ServiceClient.SelectorService.ArrayOfInt GetSelectorsResult) {
            this.GetSelectorsResult = GetSelectorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindProduct", Namespace="http://Concentrator.selectorservice.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.FindProductRequestBody Body;
        
        public FindProductRequest() {
        }
        
        public FindProductRequest(Concentrator.Web.ServiceClient.SelectorService.FindProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Concentrator.selectorservice.nl/")]
    public partial class FindProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int selectorID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string query;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int connectorID;
        
        public FindProductRequestBody() {
        }
        
        public FindProductRequestBody(int selectorID, string query, int connectorID) {
            this.selectorID = selectorID;
            this.query = query;
            this.connectorID = connectorID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindProductResponse", Namespace="http://Concentrator.selectorservice.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.FindProductResponseBody Body;
        
        public FindProductResponse() {
        }
        
        public FindProductResponse(Concentrator.Web.ServiceClient.SelectorService.FindProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Concentrator.selectorservice.nl/")]
    public partial class FindProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.ArrayOfString FindProductResult;
        
        public FindProductResponseBody() {
        }
        
        public FindProductResponseBody(Concentrator.Web.ServiceClient.SelectorService.ArrayOfString FindProductResult) {
            this.FindProductResult = FindProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindCompatibleProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindCompatibleProducts", Namespace="http://Concentrator.selectorservice.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsRequestBody Body;
        
        public FindCompatibleProductsRequest() {
        }
        
        public FindCompatibleProductsRequest(Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Concentrator.selectorservice.nl/")]
    public partial class FindCompatibleProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int selectorID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string vendorItemNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int connectorID;
        
        public FindCompatibleProductsRequestBody() {
        }
        
        public FindCompatibleProductsRequestBody(int selectorID, string vendorItemNumber, int connectorID) {
            this.selectorID = selectorID;
            this.vendorItemNumber = vendorItemNumber;
            this.connectorID = connectorID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindCompatibleProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindCompatibleProductsResponse", Namespace="http://Concentrator.selectorservice.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsResponseBody Body;
        
        public FindCompatibleProductsResponse() {
        }
        
        public FindCompatibleProductsResponse(Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Concentrator.selectorservice.nl/")]
    public partial class FindCompatibleProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.ArrayOfString FindCompatibleProductsResult;
        
        public FindCompatibleProductsResponseBody() {
        }
        
        public FindCompatibleProductsResponseBody(Concentrator.Web.ServiceClient.SelectorService.ArrayOfString FindCompatibleProductsResult) {
            this.FindCompatibleProductsResult = FindCompatibleProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSelectorProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSelectorProducts", Namespace="http://Concentrator.selectorservice.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsRequestBody Body;
        
        public GetAllSelectorProductsRequest() {
        }
        
        public GetAllSelectorProductsRequest(Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Concentrator.selectorservice.nl/")]
    public partial class GetAllSelectorProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int selectorID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int connectorID;
        
        public GetAllSelectorProductsRequestBody() {
        }
        
        public GetAllSelectorProductsRequestBody(int selectorID, int connectorID) {
            this.selectorID = selectorID;
            this.connectorID = connectorID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSelectorProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSelectorProductsResponse", Namespace="http://Concentrator.selectorservice.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsResponseBody Body;
        
        public GetAllSelectorProductsResponse() {
        }
        
        public GetAllSelectorProductsResponse(Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Concentrator.selectorservice.nl/")]
    public partial class GetAllSelectorProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllSelectorProductsResult;
        
        public GetAllSelectorProductsResponseBody() {
        }
        
        public GetAllSelectorProductsResponseBody(string GetAllSelectorProductsResult) {
            this.GetAllSelectorProductsResult = GetAllSelectorProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportSelectorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportSelectors", Namespace="http://Concentrator.selectorservice.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsRequestBody Body;
        
        public ExportSelectorsRequest() {
        }
        
        public ExportSelectorsRequest(Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExportSelectorsRequestBody {
        
        public ExportSelectorsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportSelectorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportSelectorsResponse", Namespace="http://Concentrator.selectorservice.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsResponseBody Body;
        
        public ExportSelectorsResponse() {
        }
        
        public ExportSelectorsResponse(Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Concentrator.selectorservice.nl/")]
    public partial class ExportSelectorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ExportSelectorsResult;
        
        public ExportSelectorsResponseBody() {
        }
        
        public ExportSelectorsResponseBody(System.Xml.Linq.XElement ExportSelectorsResult) {
            this.ExportSelectorsResult = ExportSelectorsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SelectorServiceSoapChannel : Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectorServiceSoapClient : System.ServiceModel.ClientBase<Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap>, Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap {
        
        public SelectorServiceSoapClient() {
        }
        
        public SelectorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SelectorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelectorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelectorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Web.ServiceClient.SelectorService.GetSelectorsResponse Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap.GetSelectors(Concentrator.Web.ServiceClient.SelectorService.GetSelectorsRequest request) {
            return base.Channel.GetSelectors(request);
        }
        
        public Concentrator.Web.ServiceClient.SelectorService.ArrayOfInt GetSelectors() {
            Concentrator.Web.ServiceClient.SelectorService.GetSelectorsRequest inValue = new Concentrator.Web.ServiceClient.SelectorService.GetSelectorsRequest();
            inValue.Body = new Concentrator.Web.ServiceClient.SelectorService.GetSelectorsRequestBody();
            Concentrator.Web.ServiceClient.SelectorService.GetSelectorsResponse retVal = ((Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap)(this)).GetSelectors(inValue);
            return retVal.Body.GetSelectorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Web.ServiceClient.SelectorService.FindProductResponse Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap.FindProduct(Concentrator.Web.ServiceClient.SelectorService.FindProductRequest request) {
            return base.Channel.FindProduct(request);
        }
        
        public Concentrator.Web.ServiceClient.SelectorService.ArrayOfString FindProduct(int selectorID, string query, int connectorID) {
            Concentrator.Web.ServiceClient.SelectorService.FindProductRequest inValue = new Concentrator.Web.ServiceClient.SelectorService.FindProductRequest();
            inValue.Body = new Concentrator.Web.ServiceClient.SelectorService.FindProductRequestBody();
            inValue.Body.selectorID = selectorID;
            inValue.Body.query = query;
            inValue.Body.connectorID = connectorID;
            Concentrator.Web.ServiceClient.SelectorService.FindProductResponse retVal = ((Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap)(this)).FindProduct(inValue);
            return retVal.Body.FindProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsResponse Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap.FindCompatibleProducts(Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsRequest request) {
            return base.Channel.FindCompatibleProducts(request);
        }
        
        public Concentrator.Web.ServiceClient.SelectorService.ArrayOfString FindCompatibleProducts(int selectorID, string vendorItemNumber, int connectorID) {
            Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsRequest inValue = new Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsRequest();
            inValue.Body = new Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsRequestBody();
            inValue.Body.selectorID = selectorID;
            inValue.Body.vendorItemNumber = vendorItemNumber;
            inValue.Body.connectorID = connectorID;
            Concentrator.Web.ServiceClient.SelectorService.FindCompatibleProductsResponse retVal = ((Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap)(this)).FindCompatibleProducts(inValue);
            return retVal.Body.FindCompatibleProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsResponse Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap.GetAllSelectorProducts(Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsRequest request) {
            return base.Channel.GetAllSelectorProducts(request);
        }
        
        public string GetAllSelectorProducts(int selectorID, int connectorID) {
            Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsRequest inValue = new Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsRequest();
            inValue.Body = new Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsRequestBody();
            inValue.Body.selectorID = selectorID;
            inValue.Body.connectorID = connectorID;
            Concentrator.Web.ServiceClient.SelectorService.GetAllSelectorProductsResponse retVal = ((Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap)(this)).GetAllSelectorProducts(inValue);
            return retVal.Body.GetAllSelectorProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsResponse Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap.ExportSelectors(Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsRequest request) {
            return base.Channel.ExportSelectors(request);
        }
        
        public System.Xml.Linq.XElement ExportSelectors() {
            Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsRequest inValue = new Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsRequest();
            inValue.Body = new Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsRequestBody();
            Concentrator.Web.ServiceClient.SelectorService.ExportSelectorsResponse retVal = ((Concentrator.Web.ServiceClient.SelectorService.SelectorServiceSoap)(this)).ExportSelectors(inValue);
            return retVal.Body.ExportSelectorsResult;
        }
    }
}
