//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concentrator.Web.ServiceClient.EDI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationCommunicationProperty", Namespace="http://edi.concentrator.nl/")]
    [System.SerializableAttribute()]
    public partial class RelationCommunicationProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BSkIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNumberField;
        
        private int RelationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderTakenByField;
        
        private System.Nullable<bool> ApplyFreightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreightProductIDField;
        
        private System.Nullable<bool> ApplyFinChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinChargesProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDIProcessorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCodeField;
        
        private System.Nullable<bool> OrderConfirmationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderConfirmationEmailField;
        
        private System.Nullable<bool> ShipmentConfirmationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipmentConfirmationEmailField;
        
        private System.Nullable<bool> InvoiceConfirmationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceConfirmationEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutboundToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutboundUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutboundPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutboundMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrormailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BSkIdentifier {
            get {
                return this.BSkIdentifierField;
            }
            set {
                if ((this.BSkIdentifierField.Equals(value) != true)) {
                    this.BSkIdentifierField = value;
                    this.RaisePropertyChanged("BSkIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SupplierNumber {
            get {
                return this.SupplierNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNumberField, value) != true)) {
                    this.SupplierNumberField = value;
                    this.RaisePropertyChanged("SupplierNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int RelationNumber {
            get {
                return this.RelationNumberField;
            }
            set {
                if ((this.RelationNumberField.Equals(value) != true)) {
                    this.RelationNumberField = value;
                    this.RaisePropertyChanged("RelationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RelationName {
            get {
                return this.RelationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationNameField, value) != true)) {
                    this.RelationNameField = value;
                    this.RaisePropertyChanged("RelationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string OrderedBy {
            get {
                return this.OrderedByField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderedByField, value) != true)) {
                    this.OrderedByField = value;
                    this.RaisePropertyChanged("OrderedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string OrderTakenBy {
            get {
                return this.OrderTakenByField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderTakenByField, value) != true)) {
                    this.OrderTakenByField = value;
                    this.RaisePropertyChanged("OrderTakenBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<bool> ApplyFreight {
            get {
                return this.ApplyFreightField;
            }
            set {
                if ((this.ApplyFreightField.Equals(value) != true)) {
                    this.ApplyFreightField = value;
                    this.RaisePropertyChanged("ApplyFreight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string FreightProductID {
            get {
                return this.FreightProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FreightProductIDField, value) != true)) {
                    this.FreightProductIDField = value;
                    this.RaisePropertyChanged("FreightProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<bool> ApplyFinCharges {
            get {
                return this.ApplyFinChargesField;
            }
            set {
                if ((this.ApplyFinChargesField.Equals(value) != true)) {
                    this.ApplyFinChargesField = value;
                    this.RaisePropertyChanged("ApplyFinCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string FinChargesProductID {
            get {
                return this.FinChargesProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FinChargesProductIDField, value) != true)) {
                    this.FinChargesProductIDField = value;
                    this.RaisePropertyChanged("FinChargesProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string EDIProcessor {
            get {
                return this.EDIProcessorField;
            }
            set {
                if ((object.ReferenceEquals(this.EDIProcessorField, value) != true)) {
                    this.EDIProcessorField = value;
                    this.RaisePropertyChanged("EDIProcessor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<bool> OrderConfirmation {
            get {
                return this.OrderConfirmationField;
            }
            set {
                if ((this.OrderConfirmationField.Equals(value) != true)) {
                    this.OrderConfirmationField = value;
                    this.RaisePropertyChanged("OrderConfirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string OrderConfirmationEmail {
            get {
                return this.OrderConfirmationEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderConfirmationEmailField, value) != true)) {
                    this.OrderConfirmationEmailField = value;
                    this.RaisePropertyChanged("OrderConfirmationEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<bool> ShipmentConfirmation {
            get {
                return this.ShipmentConfirmationField;
            }
            set {
                if ((this.ShipmentConfirmationField.Equals(value) != true)) {
                    this.ShipmentConfirmationField = value;
                    this.RaisePropertyChanged("ShipmentConfirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ShipmentConfirmationEmail {
            get {
                return this.ShipmentConfirmationEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentConfirmationEmailField, value) != true)) {
                    this.ShipmentConfirmationEmailField = value;
                    this.RaisePropertyChanged("ShipmentConfirmationEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<bool> InvoiceConfirmation {
            get {
                return this.InvoiceConfirmationField;
            }
            set {
                if ((this.InvoiceConfirmationField.Equals(value) != true)) {
                    this.InvoiceConfirmationField = value;
                    this.RaisePropertyChanged("InvoiceConfirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string InvoiceConfirmationEmail {
            get {
                return this.InvoiceConfirmationEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceConfirmationEmailField, value) != true)) {
                    this.InvoiceConfirmationEmailField = value;
                    this.RaisePropertyChanged("InvoiceConfirmationEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string ConnectorType {
            get {
                return this.ConnectorTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectorTypeField, value) != true)) {
                    this.ConnectorTypeField = value;
                    this.RaisePropertyChanged("ConnectorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string OutboundTo {
            get {
                return this.OutboundToField;
            }
            set {
                if ((object.ReferenceEquals(this.OutboundToField, value) != true)) {
                    this.OutboundToField = value;
                    this.RaisePropertyChanged("OutboundTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string OutboundUsername {
            get {
                return this.OutboundUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.OutboundUsernameField, value) != true)) {
                    this.OutboundUsernameField = value;
                    this.RaisePropertyChanged("OutboundUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string OutboundPassword {
            get {
                return this.OutboundPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.OutboundPasswordField, value) != true)) {
                    this.OutboundPasswordField = value;
                    this.RaisePropertyChanged("OutboundPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string OutboundMessageType {
            get {
                return this.OutboundMessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OutboundMessageTypeField, value) != true)) {
                    this.OutboundMessageTypeField = value;
                    this.RaisePropertyChanged("OutboundMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Errormail {
            get {
                return this.ErrormailField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrormailField, value) != true)) {
                    this.ErrormailField = value;
                    this.RaisePropertyChanged("Errormail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string BusinessUnit {
            get {
                return this.BusinessUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessUnitField, value) != true)) {
                    this.BusinessUnitField = value;
                    this.RaisePropertyChanged("BusinessUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string SearchType {
            get {
                return this.SearchTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchTypeField, value) != true)) {
                    this.SearchTypeField = value;
                    this.RaisePropertyChanged("SearchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edi.concentrator.nl/", ConfigurationName="EDI.CommunicationServiceSoap")]
    public interface CommunicationServiceSoap {
        
        // CODEGEN: Generating message contract since element name property from namespace http://edi.concentrator.nl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edi.concentrator.nl/UpdateRelationSettings", ReplyAction="*")]
        Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsResponse UpdateRelationSettings(Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsRequest request);
        
        // CODEGEN: Generating message contract since element name GetRelationSettingsResult from namespace http://edi.concentrator.nl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edi.concentrator.nl/GetRelationSettings", ReplyAction="*")]
        Concentrator.Web.ServiceClient.EDI.GetRelationSettingsResponse GetRelationSettings(Concentrator.Web.ServiceClient.EDI.GetRelationSettingsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRelationSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRelationSettings", Namespace="http://edi.concentrator.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsRequestBody Body;
        
        public UpdateRelationSettingsRequest() {
        }
        
        public UpdateRelationSettingsRequest(Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edi.concentrator.nl/")]
    public partial class UpdateRelationSettingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Concentrator.Web.ServiceClient.EDI.RelationCommunicationProperty property;
        
        public UpdateRelationSettingsRequestBody() {
        }
        
        public UpdateRelationSettingsRequestBody(Concentrator.Web.ServiceClient.EDI.RelationCommunicationProperty property) {
            this.property = property;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRelationSettingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRelationSettingsResponse", Namespace="http://edi.concentrator.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsResponseBody Body;
        
        public UpdateRelationSettingsResponse() {
        }
        
        public UpdateRelationSettingsResponse(Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateRelationSettingsResponseBody {
        
        public UpdateRelationSettingsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRelationSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRelationSettings", Namespace="http://edi.concentrator.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.EDI.GetRelationSettingsRequestBody Body;
        
        public GetRelationSettingsRequest() {
        }
        
        public GetRelationSettingsRequest(Concentrator.Web.ServiceClient.EDI.GetRelationSettingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRelationSettingsRequestBody {
        
        public GetRelationSettingsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRelationSettingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRelationSettingsResponse", Namespace="http://edi.concentrator.nl/", Order=0)]
        public Concentrator.Web.ServiceClient.EDI.GetRelationSettingsResponseBody Body;
        
        public GetRelationSettingsResponse() {
        }
        
        public GetRelationSettingsResponse(Concentrator.Web.ServiceClient.EDI.GetRelationSettingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edi.concentrator.nl/")]
    public partial class GetRelationSettingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRelationSettingsResult;
        
        public GetRelationSettingsResponseBody() {
        }
        
        public GetRelationSettingsResponseBody(string GetRelationSettingsResult) {
            this.GetRelationSettingsResult = GetRelationSettingsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface CommunicationServiceSoapChannel : Concentrator.Web.ServiceClient.EDI.CommunicationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CommunicationServiceSoapClient : System.ServiceModel.ClientBase<Concentrator.Web.ServiceClient.EDI.CommunicationServiceSoap>, Concentrator.Web.ServiceClient.EDI.CommunicationServiceSoap {
        
        public CommunicationServiceSoapClient() {
        }
        
        public CommunicationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommunicationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsResponse Concentrator.Web.ServiceClient.EDI.CommunicationServiceSoap.UpdateRelationSettings(Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsRequest request) {
            return base.Channel.UpdateRelationSettings(request);
        }
        
        public void UpdateRelationSettings(Concentrator.Web.ServiceClient.EDI.RelationCommunicationProperty property) {
            Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsRequest inValue = new Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsRequest();
            inValue.Body = new Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsRequestBody();
            inValue.Body.property = property;
            Concentrator.Web.ServiceClient.EDI.UpdateRelationSettingsResponse retVal = ((Concentrator.Web.ServiceClient.EDI.CommunicationServiceSoap)(this)).UpdateRelationSettings(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Web.ServiceClient.EDI.GetRelationSettingsResponse Concentrator.Web.ServiceClient.EDI.CommunicationServiceSoap.GetRelationSettings(Concentrator.Web.ServiceClient.EDI.GetRelationSettingsRequest request) {
            return base.Channel.GetRelationSettings(request);
        }
        
        public string GetRelationSettings() {
            Concentrator.Web.ServiceClient.EDI.GetRelationSettingsRequest inValue = new Concentrator.Web.ServiceClient.EDI.GetRelationSettingsRequest();
            inValue.Body = new Concentrator.Web.ServiceClient.EDI.GetRelationSettingsRequestBody();
            Concentrator.Web.ServiceClient.EDI.GetRelationSettingsResponse retVal = ((Concentrator.Web.ServiceClient.EDI.CommunicationServiceSoap)(this)).GetRelationSettings(inValue);
            return retVal.Body.GetRelationSettingsResult;
        }
    }
}
