//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concentrator.Plugins.Alatest.AlatestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlatestService.IAlatestService")]
    public interface IAlatestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlatestService/GetReview", ReplyAction="http://tempuri.org/IAlatestService/GetReviewResponse")]
        string GetReview(string queryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlatestService/GetRating", ReplyAction="http://tempuri.org/IAlatestService/GetRatingResponse")]
        string GetRating(string queryString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlatestServiceChannel : Concentrator.Plugins.Alatest.AlatestService.IAlatestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlatestServiceClient : System.ServiceModel.ClientBase<Concentrator.Plugins.Alatest.AlatestService.IAlatestService>, Concentrator.Plugins.Alatest.AlatestService.IAlatestService {
        
        public AlatestServiceClient() {
        }
        
        public AlatestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlatestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlatestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlatestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetReview(string queryString) {
            return base.Channel.GetReview(queryString);
        }
        
        public string GetRating(string queryString) {
            return base.Channel.GetRating(queryString);
        }
    }
}
