<?xml version="1.0" encoding="utf-8"?>
<Database Name="Bram_Dev_Test" Class="AuctionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=bramlivesrv;Initial Catalog=Bram_Dev_Test;Persist Security Info=True;User ID=replication" SettingsObjectName="Spider.VeilingImport.Properties.Settings" SettingsPropertyName="Bram_Dev_TestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AuctionProducts" Member="AuctionProducts">
    <Type Name="AuctionProduct">
      <Column Name="AuctionProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AuctionBSCStock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AuctionOEMStock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AuctionDC10Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockStatus" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="QuantityToReceive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DC10CostPrice" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="BSCCostPrice" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Association Name="Product_AuctionProduct" Member="Product" ThisKey="AuctionProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShortDescription" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LongDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ManufacturerID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BrandID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaxRateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="UnitCost" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="LedgerClass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsCustom" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LineType" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="ProductStatus" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExtendedCatalog" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PromisedDeliveryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CanModifyPrice" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModificationTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ProductDesk" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PromisedDeliveryDateOverride" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BackEndDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Product_AuctionProduct" Member="AuctionProduct" ThisKey="ProductID" OtherKey="AuctionProductID" Type="AuctionProduct" Cardinality="One" />
      <Association Name="Brand_Product" Member="Brand" ThisKey="BrandID" OtherKey="BrandID" Type="Brand" IsForeignKey="true" />
      <Association Name="TaxRate_Product" Member="TaxRate" ThisKey="TaxRateID" OtherKey="TaxRateID" Type="TaxRate" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Brands" Member="Brands">
    <Type Name="Brand">
      <Column Name="BrandID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BrandCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BrandWebsite" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModificationTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Brand_Product" Member="Products" ThisKey="BrandID" OtherKey="BrandID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.TaxRates" Member="TaxRates">
    <Type Name="TaxRate">
      <Column Name="TaxRateID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaxRate" Member="TaxRate1" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LedgerClass" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModificationTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TaxRate_Product" Member="Products" ThisKey="TaxRateID" OtherKey="TaxRateID" Type="Product" />
    </Type>
  </Table>
</Database>