declare @materialAttributeID int

set @materialAttributeID = (select AttributeID from ProductAttributeMetaData
							where AttributeCode = 'Material' 
							and VendorID = 48) 


if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Acryl' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Acryl')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Badstof' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Badstof')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Canvas' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Canvas')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Corduroy' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Corduroy')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Denim' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Denim')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'flanel' ) insert into ProductAttributeOption  values (@materialAttributeID, 'flanel')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Fleece' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Fleece')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Fluweel' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Fluweel')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Imitatie bont' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Imitatie bont')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Jersey' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Jersey')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Katoen' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Katoen')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Katoen/polyester' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Katoen/polyester')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Katoensatijn' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Katoensatijn')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Kunststof' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Kunststof')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Lederlook' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Lederlook')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Leer' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Leer')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Linnen' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Linnen')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Linnen/katoen' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Linnen/katoen')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Nubuck' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Nubuck')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Nylon' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Nylon')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Polyacryl' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Polyacryl')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Polyamide' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Polyamide')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Polyester' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Polyester')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Polyether' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Polyether')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Polyurethaan' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Polyurethaan')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Satijn' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Satijn')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Stof' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Stof')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Stretchdenim' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Stretchdenim')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Stretchkatoen' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Stretchkatoen')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Suede' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Suede')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Suedelook' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Suedelook')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Synthetisch' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Synthetisch')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Tweed' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Tweed')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Velours' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Velours')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Vilt' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Vilt')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Viscose' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Viscose')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Wol' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Wol')
if not exists (select * from ProductAttributeOption where attributeID = @materialAttributeID and AttributeOption = 'Zijde' ) insert into ProductAttributeOption  values (@materialAttributeID, 'Zijde')
