declare @dessinAttributeID int

set @dessinAttributeID = (select AttributeID from ProductAttributeMetaData
							where AttributeCode = 'Dessin' 
							and VendorID = 48) 

if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Afstekend biesje') insert into ProductAttributeOption  values (@dessinAttributeID, 'Afstekend biesje ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Mix & Match' ) insert into ProductAttributeOption  values (@dessinAttributeID, 'Mix & Match')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'All') insert into ProductAttributeOption  values (@dessinAttributeID, 'All ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'All over print') insert into ProductAttributeOption  values (@dessinAttributeID, 'All over print ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Barok') insert into ProductAttributeOption  values (@dessinAttributeID, 'Barok ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Batik') insert into ProductAttributeOption  values (@dessinAttributeID, 'Batik ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Blad') insert into ProductAttributeOption  values (@dessinAttributeID, 'Blad ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Bloemen') insert into ProductAttributeOption  values (@dessinAttributeID, 'Bloemen ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Borduursel') insert into ProductAttributeOption  values (@dessinAttributeID, 'Borduursel ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Borduursels') insert into ProductAttributeOption  values (@dessinAttributeID, 'Borduursels ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Camouflage (army)') insert into ProductAttributeOption  values (@dessinAttributeID, 'Camouflage (army) ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Camouflage(army)/jungle/safari') insert into ProductAttributeOption  values (@dessinAttributeID, 'Camouflage(army)/jungle/safari ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Cartoon') insert into ProductAttributeOption  values (@dessinAttributeID, 'Cartoon ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Cirkel') insert into ProductAttributeOption  values (@dessinAttributeID, 'Cirkel ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Crinkle') insert into ProductAttributeOption  values (@dessinAttributeID, 'Crinkle ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Crocoprint') insert into ProductAttributeOption  values (@dessinAttributeID, 'Crocoprint ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Dames') insert into ProductAttributeOption  values (@dessinAttributeID, 'Dames ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Dieren') insert into ProductAttributeOption  values (@dessinAttributeID, 'Dieren ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Dierenprint') insert into ProductAttributeOption  values (@dessinAttributeID, 'Dierenprint ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Fruit') insert into ProductAttributeOption  values (@dessinAttributeID, 'Fruit ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Glitter/Goud/Zilveropdruk') insert into ProductAttributeOption  values (@dessinAttributeID, 'Glitter/Goud/Zilveropdruk ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Glitters') insert into ProductAttributeOption  values (@dessinAttributeID, 'Glitters ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Grafisch') insert into ProductAttributeOption  values (@dessinAttributeID, 'Grafisch ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Grand') insert into ProductAttributeOption  values (@dessinAttributeID, 'Grand ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Hawai') insert into ProductAttributeOption  values (@dessinAttributeID, 'Hawai ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Honingraat') insert into ProductAttributeOption  values (@dessinAttributeID, 'Honingraat ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Houtstructuur') insert into ProductAttributeOption  values (@dessinAttributeID, 'Houtstructuur ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Immitatie bont' ) insert into ProductAttributeOption  values (@dessinAttributeID, 'Immitatie bont')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Jacquard') insert into ProductAttributeOption  values (@dessinAttributeID, 'Jacquard ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Kabels') insert into ProductAttributeOption  values (@dessinAttributeID, 'Kabels ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Kant') insert into ProductAttributeOption  values (@dessinAttributeID, 'Kant ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Kraaltjes/studs') insert into ProductAttributeOption  values (@dessinAttributeID, 'Kraaltjes/studs ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Krijtstreep') insert into ProductAttributeOption  values (@dessinAttributeID, 'Krijtstreep ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Lak') insert into ProductAttributeOption  values (@dessinAttributeID, 'Lak ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Letters/opdruk/print') insert into ProductAttributeOption  values (@dessinAttributeID, 'Letters/opdruk/print ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Liberty') insert into ProductAttributeOption  values (@dessinAttributeID, 'Liberty ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Luxe (kantjes/bandjes)') insert into ProductAttributeOption  values (@dessinAttributeID, 'Luxe (kantjes/bandjes) ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Maritiem') insert into ProductAttributeOption  values (@dessinAttributeID, 'Maritiem ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Melee') insert into ProductAttributeOption  values (@dessinAttributeID, 'Melee ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Mickey / Minnie Mouse') insert into ProductAttributeOption  values (@dessinAttributeID, 'Mickey / Minnie Mouse ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Mixprint') insert into ProductAttributeOption  values (@dessinAttributeID, 'Mixprint ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'N.v.t.') insert into ProductAttributeOption  values (@dessinAttributeID, 'N.v.t. ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Noorwegen') insert into ProductAttributeOption  values (@dessinAttributeID, 'Noorwegen ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Orientaals') insert into ProductAttributeOption  values (@dessinAttributeID, 'Orientaals ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Ornament') insert into ProductAttributeOption  values (@dessinAttributeID, 'Ornament ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Paard') insert into ProductAttributeOption  values (@dessinAttributeID, 'Paard ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Paisley(kashmir)') insert into ProductAttributeOption  values (@dessinAttributeID, 'Paisley(kashmir) ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Patchwork') insert into ProductAttributeOption  values (@dessinAttributeID, 'Patchwork ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Print') insert into ProductAttributeOption  values (@dessinAttributeID, 'Print ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Print all over') insert into ProductAttributeOption  values (@dessinAttributeID, 'Print all over ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Printopdruk') insert into ProductAttributeOption  values (@dessinAttributeID, 'Printopdruk ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Randdessin') insert into ProductAttributeOption  values (@dessinAttributeID, 'Randdessin ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Rondjes') insert into ProductAttributeOption  values (@dessinAttributeID, 'Rondjes ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Ruit') insert into ProductAttributeOption  values (@dessinAttributeID, 'Ruit ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'South Park') insert into ProductAttributeOption  values (@dessinAttributeID, 'South Park ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Stempel') insert into ProductAttributeOption  values (@dessinAttributeID, 'Stempel ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Sterren/Zon/Maan') insert into ProductAttributeOption  values (@dessinAttributeID, 'Sterren/Zon/Maan ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Stip' ) insert into ProductAttributeOption  values (@dessinAttributeID, 'Stip')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Strass/spiegeltjes/pailletjes') insert into ProductAttributeOption  values (@dessinAttributeID, 'Strass/spiegeltjes/pailletjes ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Streep') insert into ProductAttributeOption  values (@dessinAttributeID, 'Streep ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Strikje') insert into ProductAttributeOption  values (@dessinAttributeID, 'Strikje ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Tekst') insert into ProductAttributeOption  values (@dessinAttributeID, 'Tekst ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Tie-dye') insert into ProductAttributeOption  values (@dessinAttributeID, 'Tie-dye ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Tweekleurig') insert into ProductAttributeOption  values (@dessinAttributeID, 'Tweekleurig ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Uni') insert into ProductAttributeOption  values (@dessinAttributeID, 'Uni ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Visgraat') insert into ProductAttributeOption  values (@dessinAttributeID, 'Visgraat ')
if not exists (select * from ProductAttributeOption where attributeID = @dessinAttributeID and AttributeOption = 'Vlag') insert into ProductAttributeOption  values (@dessinAttributeID, 'Vlag ')
