//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concentrator.Objects.RED {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://protexis.com/webservices", ConfigurationName="RED.RetailerSoap")]
    public interface RetailerSoap {
        
        // CODEGEN: Generating message contract since message BeginOrderReservationRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/BeginOrderReservationRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.BeginOrderReservationRequestResponse BeginOrderReservationRequest(Concentrator.Objects.RED.BeginOrderReservationRequestRequest request);
        
        // CODEGEN: Generating message contract since message AddOrderItemRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/AddOrderItemRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.AddOrderItemRequestResponse AddOrderItemRequest(Concentrator.Objects.RED.AddOrderItemRequestRequest request);
        
        // CODEGEN: Generating message contract since message CompleteOrderReservationRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/CompleteOrderReservationRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.CompleteOrderReservationRequestResponse CompleteOrderReservationRequest(Concentrator.Objects.RED.CompleteOrderReservationRequestRequest request);
        
        // CODEGEN: Generating message contract since message OrderShipmentRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/OrderShipmentRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.OrderShipmentRequestResponse OrderShipmentRequest(Concentrator.Objects.RED.OrderShipmentRequestRequest request);
        
        // CODEGEN: Generating message contract since message CancelOrderReservationRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/CancelOrderReservationRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.CancelOrderReservationRequestResponse CancelOrderReservationRequest(Concentrator.Objects.RED.CancelOrderReservationRequestRequest request);
        
        // CODEGEN: Generating message contract since message CommitToPurchaseOrderRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/CommitToPurchaseOrderRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.CommitToPurchaseOrderRequestResponse CommitToPurchaseOrderRequest(Concentrator.Objects.RED.CommitToPurchaseOrderRequestRequest request);
        
        // CODEGEN: Generating message contract since message PurchaseOrderItemFulfillmentRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/PurchaseOrderItemFulfillmentRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.PurchaseOrderItemFulfillmentRequestResponse PurchaseOrderItemFulfillmentRequest(Concentrator.Objects.RED.PurchaseOrderItemFulfillmentRequestRequest request);
        
        // CODEGEN: Generating message contract since message PurchaseOrderItemFulfillmentDetailRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/PurchaseOrderItemFulfillmentDetailRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.PurchaseOrderItemFulfillmentDetailRequestResponse PurchaseOrderItemFulfillmentDetailRequest(Concentrator.Objects.RED.PurchaseOrderItemFulfillmentDetailRequestRequest request);
        
        // CODEGEN: Generating message contract since message SecurePackageToleranceAdjustmentRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/SecurePackageToleranceAdjustmentRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.SecurePackageToleranceAdjustmentRequestResponse SecurePackageToleranceAdjustmentRequest(Concentrator.Objects.RED.SecurePackageToleranceAdjustmentRequestRequest request);
        
        // CODEGEN: Generating message contract since message SerialNumberToleranceAdjustmentRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/SerialNumberToleranceAdjustmentRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.SerialNumberToleranceAdjustmentRequestResponse SerialNumberToleranceAdjustmentRequest(Concentrator.Objects.RED.SerialNumberToleranceAdjustmentRequestRequest request);
        
        // CODEGEN: Generating message contract since message PurchaseOrderItemRefundRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/PurchaseOrderItemRefundRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.PurchaseOrderItemRefundRequestResponse PurchaseOrderItemRefundRequest(Concentrator.Objects.RED.PurchaseOrderItemRefundRequestRequest request);
        
        // CODEGEN: Generating message contract since message PurchaseOrderChargebackRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/PurchaseOrderChargebackRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.PurchaseOrderChargebackRequestResponse PurchaseOrderChargebackRequest(Concentrator.Objects.RED.PurchaseOrderChargebackRequestRequest request);
        
        // CODEGEN: Generating message contract since message GetCatalogUrlRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/GetCatalogUrlRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.GetCatalogUrlRequestResponse GetCatalogUrlRequest(Concentrator.Objects.RED.GetCatalogUrlRequestRequest request);
        
        // CODEGEN: Generating message contract since message CatalogResponseRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/CatalogResponseRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.CatalogResponseRequestResponse CatalogResponseRequest(Concentrator.Objects.RED.CatalogResponseRequestRequest request);
        
        // CODEGEN: Generating message contract since message GetInvoiceBatchUrlRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/GetInvoiceBatchUrlRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.GetInvoiceBatchUrlRequestResponse GetInvoiceBatchUrlRequest(Concentrator.Objects.RED.GetInvoiceBatchUrlRequestRequest request);
        
        // CODEGEN: Generating message contract since message InvoiceResponseRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/InvoiceResponseRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.InvoiceResponseRequestResponse InvoiceResponseRequest(Concentrator.Objects.RED.InvoiceResponseRequestRequest request);
        
        // CODEGEN: Generating message contract since message DigitalReceiptRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://protexis.com/webservices/DigitalReceiptRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.Objects.RED.DigitalReceiptRequestResponse DigitalReceiptRequest(Concentrator.Objects.RED.DigitalReceiptRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://protexis.com/webservices")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string signatureField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BeginOrderReservationRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class BeginOrderReservationRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Order_ID;
        
        public BeginOrderReservationRequestRequest() {
        }
        
        public BeginOrderReservationRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Order_ID) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Order_ID = Order_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BeginOrderReservationRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class BeginOrderReservationRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string BeginOrderReservationRequestResult;
        
        public BeginOrderReservationRequestResponse() {
        }
        
        public BeginOrderReservationRequestResponse(string BeginOrderReservationRequestResult) {
            this.BeginOrderReservationRequestResult = BeginOrderReservationRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrderItemRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class AddOrderItemRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Order_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=1)]
        public string Line_Item_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=2)]
        public string Offer_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=3)]
        public decimal Sale_Price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=4)]
        public string Curreny_Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=5)]
        public int Quantity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=6)]
        public string Brand_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=7)]
        public string Promotion_Code;
        
        public AddOrderItemRequestRequest() {
        }
        
        public AddOrderItemRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Order_ID, string Line_Item_ID, string Offer_ID, decimal Sale_Price, string Curreny_Code, int Quantity, string Brand_ID, string Promotion_Code) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Order_ID = Order_ID;
            this.Line_Item_ID = Line_Item_ID;
            this.Offer_ID = Offer_ID;
            this.Sale_Price = Sale_Price;
            this.Curreny_Code = Curreny_Code;
            this.Quantity = Quantity;
            this.Brand_ID = Brand_ID;
            this.Promotion_Code = Promotion_Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrderItemRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class AddOrderItemRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string AddOrderItemRequestResult;
        
        public AddOrderItemRequestResponse() {
        }
        
        public AddOrderItemRequestResponse(string AddOrderItemRequestResult) {
            this.AddOrderItemRequestResult = AddOrderItemRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CompleteOrderReservationRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class CompleteOrderReservationRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Order_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=1)]
        public string Reservation_Hold_Hours;
        
        public CompleteOrderReservationRequestRequest() {
        }
        
        public CompleteOrderReservationRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Order_ID, string Reservation_Hold_Hours) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Order_ID = Order_ID;
            this.Reservation_Hold_Hours = Reservation_Hold_Hours;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CompleteOrderReservationRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class CompleteOrderReservationRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string CompleteOrderReservationRequestResult;
        
        public CompleteOrderReservationRequestResponse() {
        }
        
        public CompleteOrderReservationRequestResponse(string CompleteOrderReservationRequestResult) {
            this.CompleteOrderReservationRequestResult = CompleteOrderReservationRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderShipmentRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class OrderShipmentRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Request_Xml;
        
        public OrderShipmentRequestRequest() {
        }
        
        public OrderShipmentRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Request_Xml) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Request_Xml = Request_Xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderShipmentRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class OrderShipmentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string OrderShipmentRequestResult;
        
        public OrderShipmentRequestResponse() {
        }
        
        public OrderShipmentRequestResponse(string OrderShipmentRequestResult) {
            this.OrderShipmentRequestResult = OrderShipmentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelOrderReservationRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class CancelOrderReservationRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Order_ID;
        
        public CancelOrderReservationRequestRequest() {
        }
        
        public CancelOrderReservationRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Order_ID) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Order_ID = Order_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelOrderReservationRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class CancelOrderReservationRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string CancelOrderReservationRequestResult;
        
        public CancelOrderReservationRequestResponse() {
        }
        
        public CancelOrderReservationRequestResponse(string CancelOrderReservationRequestResult) {
            this.CancelOrderReservationRequestResult = CancelOrderReservationRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CommitToPurchaseOrderRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class CommitToPurchaseOrderRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Order_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=1)]
        public string Purchase_Order_ID;
        
        public CommitToPurchaseOrderRequestRequest() {
        }
        
        public CommitToPurchaseOrderRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Order_ID, string Purchase_Order_ID) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Order_ID = Order_ID;
            this.Purchase_Order_ID = Purchase_Order_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CommitToPurchaseOrderRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class CommitToPurchaseOrderRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string CommitToPurchaseOrderRequestResult;
        
        public CommitToPurchaseOrderRequestResponse() {
        }
        
        public CommitToPurchaseOrderRequestResponse(string CommitToPurchaseOrderRequestResult) {
            this.CommitToPurchaseOrderRequestResult = CommitToPurchaseOrderRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PurchaseOrderItemFulfillmentRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class PurchaseOrderItemFulfillmentRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Purchase_Order_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=1)]
        public string Line_Item_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=2)]
        public string Language_Code;
        
        public PurchaseOrderItemFulfillmentRequestRequest() {
        }
        
        public PurchaseOrderItemFulfillmentRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID, string Line_Item_ID, string Language_Code) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Purchase_Order_ID = Purchase_Order_ID;
            this.Line_Item_ID = Line_Item_ID;
            this.Language_Code = Language_Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PurchaseOrderItemFulfillmentRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class PurchaseOrderItemFulfillmentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string PurchaseOrderItemFulfillmentRequestResult;
        
        public PurchaseOrderItemFulfillmentRequestResponse() {
        }
        
        public PurchaseOrderItemFulfillmentRequestResponse(string PurchaseOrderItemFulfillmentRequestResult) {
            this.PurchaseOrderItemFulfillmentRequestResult = PurchaseOrderItemFulfillmentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PurchaseOrderItemFulfillmentDetailRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class PurchaseOrderItemFulfillmentDetailRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Purchase_Order_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=1)]
        public string Line_Item_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=2)]
        public string Language_Code;
        
        public PurchaseOrderItemFulfillmentDetailRequestRequest() {
        }
        
        public PurchaseOrderItemFulfillmentDetailRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID, string Line_Item_ID, string Language_Code) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Purchase_Order_ID = Purchase_Order_ID;
            this.Line_Item_ID = Line_Item_ID;
            this.Language_Code = Language_Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PurchaseOrderItemFulfillmentDetailRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class PurchaseOrderItemFulfillmentDetailRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string PurchaseOrderItemFulfillmentDetailRequestResult;
        
        public PurchaseOrderItemFulfillmentDetailRequestResponse() {
        }
        
        public PurchaseOrderItemFulfillmentDetailRequestResponse(string PurchaseOrderItemFulfillmentDetailRequestResult) {
            this.PurchaseOrderItemFulfillmentDetailRequestResult = PurchaseOrderItemFulfillmentDetailRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SecurePackageToleranceAdjustmentRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class SecurePackageToleranceAdjustmentRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Purchase_Order_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=1)]
        public string Line_Item_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=2)]
        public string Support_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=3)]
        public int Unlock_Limit_Total;
        
        public SecurePackageToleranceAdjustmentRequestRequest() {
        }
        
        public SecurePackageToleranceAdjustmentRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID, string Line_Item_ID, string Support_ID, int Unlock_Limit_Total) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Purchase_Order_ID = Purchase_Order_ID;
            this.Line_Item_ID = Line_Item_ID;
            this.Support_ID = Support_ID;
            this.Unlock_Limit_Total = Unlock_Limit_Total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SecurePackageToleranceAdjustmentRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class SecurePackageToleranceAdjustmentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string SecurePackageToleranceAdjustmentRequestResult;
        
        public SecurePackageToleranceAdjustmentRequestResponse() {
        }
        
        public SecurePackageToleranceAdjustmentRequestResponse(string SecurePackageToleranceAdjustmentRequestResult) {
            this.SecurePackageToleranceAdjustmentRequestResult = SecurePackageToleranceAdjustmentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SerialNumberToleranceAdjustmentRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class SerialNumberToleranceAdjustmentRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Purchase_Order_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=1)]
        public string Line_Item_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=2)]
        public string Serial_Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=3)]
        public string Support_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=4)]
        public int Activation_Limit_Total;
        
        public SerialNumberToleranceAdjustmentRequestRequest() {
        }
        
        public SerialNumberToleranceAdjustmentRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID, string Line_Item_ID, string Serial_Number, string Support_ID, int Activation_Limit_Total) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Purchase_Order_ID = Purchase_Order_ID;
            this.Line_Item_ID = Line_Item_ID;
            this.Serial_Number = Serial_Number;
            this.Support_ID = Support_ID;
            this.Activation_Limit_Total = Activation_Limit_Total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SerialNumberToleranceAdjustmentRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class SerialNumberToleranceAdjustmentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string SerialNumberToleranceAdjustmentRequestResult;
        
        public SerialNumberToleranceAdjustmentRequestResponse() {
        }
        
        public SerialNumberToleranceAdjustmentRequestResponse(string SerialNumberToleranceAdjustmentRequestResult) {
            this.SerialNumberToleranceAdjustmentRequestResult = SerialNumberToleranceAdjustmentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PurchaseOrderItemRefundRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class PurchaseOrderItemRefundRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Purchase_Order_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=1)]
        public string Line_Item_ID;
        
        public PurchaseOrderItemRefundRequestRequest() {
        }
        
        public PurchaseOrderItemRefundRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID, string Line_Item_ID) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Purchase_Order_ID = Purchase_Order_ID;
            this.Line_Item_ID = Line_Item_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PurchaseOrderItemRefundRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class PurchaseOrderItemRefundRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string PurchaseOrderItemRefundRequestResult;
        
        public PurchaseOrderItemRefundRequestResponse() {
        }
        
        public PurchaseOrderItemRefundRequestResponse(string PurchaseOrderItemRefundRequestResult) {
            this.PurchaseOrderItemRefundRequestResult = PurchaseOrderItemRefundRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PurchaseOrderChargebackRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class PurchaseOrderChargebackRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Purchase_Order_ID;
        
        public PurchaseOrderChargebackRequestRequest() {
        }
        
        public PurchaseOrderChargebackRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Purchase_Order_ID = Purchase_Order_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PurchaseOrderChargebackRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class PurchaseOrderChargebackRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string PurchaseOrderChargebackRequestResult;
        
        public PurchaseOrderChargebackRequestResponse() {
        }
        
        public PurchaseOrderChargebackRequestResponse(string PurchaseOrderChargebackRequestResult) {
            this.PurchaseOrderChargebackRequestResult = PurchaseOrderChargebackRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCatalogUrlRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class GetCatalogUrlRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Catalog_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=1)]
        public string Catalog_Code;
        
        public GetCatalogUrlRequestRequest() {
        }
        
        public GetCatalogUrlRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Catalog_ID, string Catalog_Code) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Catalog_ID = Catalog_ID;
            this.Catalog_Code = Catalog_Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCatalogUrlRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class GetCatalogUrlRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string GetCatalogUrlRequestResult;
        
        public GetCatalogUrlRequestResponse() {
        }
        
        public GetCatalogUrlRequestResponse(string GetCatalogUrlRequestResult) {
            this.GetCatalogUrlRequestResult = GetCatalogUrlRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CatalogResponseRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class CatalogResponseRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Response_XML;
        
        public CatalogResponseRequestRequest() {
        }
        
        public CatalogResponseRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Response_XML) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Response_XML = Response_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CatalogResponseRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class CatalogResponseRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string CatalogResponseRequestResult;
        
        public CatalogResponseRequestResponse() {
        }
        
        public CatalogResponseRequestResponse(string CatalogResponseRequestResult) {
            this.CatalogResponseRequestResult = CatalogResponseRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInvoiceBatchUrlRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class GetInvoiceBatchUrlRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Batch_Control_Number;
        
        public GetInvoiceBatchUrlRequestRequest() {
        }
        
        public GetInvoiceBatchUrlRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Batch_Control_Number) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Batch_Control_Number = Batch_Control_Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInvoiceBatchUrlRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class GetInvoiceBatchUrlRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string GetInvoiceBatchUrlRequestResult;
        
        public GetInvoiceBatchUrlRequestResponse() {
        }
        
        public GetInvoiceBatchUrlRequestResponse(string GetInvoiceBatchUrlRequestResult) {
            this.GetInvoiceBatchUrlRequestResult = GetInvoiceBatchUrlRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InvoiceResponseRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class InvoiceResponseRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Invoice_Response_Xml;
        
        public InvoiceResponseRequestRequest() {
        }
        
        public InvoiceResponseRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Invoice_Response_Xml) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Invoice_Response_Xml = Invoice_Response_Xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InvoiceResponseRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class InvoiceResponseRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string InvoiceResponseRequestResult;
        
        public InvoiceResponseRequestResponse() {
        }
        
        public InvoiceResponseRequestResponse(string InvoiceResponseRequestResult) {
            this.InvoiceResponseRequestResult = InvoiceResponseRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DigitalReceiptRequest", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class DigitalReceiptRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://protexis.com/webservices")]
        public Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string Support_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=1)]
        public string Platform_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=2)]
        public string Version_ID;
        
        public DigitalReceiptRequestRequest() {
        }
        
        public DigitalReceiptRequestRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Support_ID, string Platform_ID, string Version_ID) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Support_ID = Support_ID;
            this.Platform_ID = Platform_ID;
            this.Version_ID = Version_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DigitalReceiptRequestResponse", WrapperNamespace="http://protexis.com/webservices", IsWrapped=true)]
    public partial class DigitalReceiptRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://protexis.com/webservices", Order=0)]
        public string DigitalReceiptRequestResult;
        
        public DigitalReceiptRequestResponse() {
        }
        
        public DigitalReceiptRequestResponse(string DigitalReceiptRequestResult) {
            this.DigitalReceiptRequestResult = DigitalReceiptRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RetailerSoapChannel : Concentrator.Objects.RED.RetailerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RetailerSoapClient : System.ServiceModel.ClientBase<Concentrator.Objects.RED.RetailerSoap>, Concentrator.Objects.RED.RetailerSoap {
        
        public RetailerSoapClient() {
        }
        
        public RetailerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetailerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetailerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetailerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.BeginOrderReservationRequestResponse Concentrator.Objects.RED.RetailerSoap.BeginOrderReservationRequest(Concentrator.Objects.RED.BeginOrderReservationRequestRequest request) {
            return base.Channel.BeginOrderReservationRequest(request);
        }
        
        public string BeginOrderReservationRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Order_ID) {
            Concentrator.Objects.RED.BeginOrderReservationRequestRequest inValue = new Concentrator.Objects.RED.BeginOrderReservationRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Order_ID = Order_ID;
            Concentrator.Objects.RED.BeginOrderReservationRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).BeginOrderReservationRequest(inValue);
            return retVal.BeginOrderReservationRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.AddOrderItemRequestResponse Concentrator.Objects.RED.RetailerSoap.AddOrderItemRequest(Concentrator.Objects.RED.AddOrderItemRequestRequest request) {
            return base.Channel.AddOrderItemRequest(request);
        }
        
        public string AddOrderItemRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Order_ID, string Line_Item_ID, string Offer_ID, decimal Sale_Price, string Curreny_Code, int Quantity, string Brand_ID, string Promotion_Code) {
            Concentrator.Objects.RED.AddOrderItemRequestRequest inValue = new Concentrator.Objects.RED.AddOrderItemRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Order_ID = Order_ID;
            inValue.Line_Item_ID = Line_Item_ID;
            inValue.Offer_ID = Offer_ID;
            inValue.Sale_Price = Sale_Price;
            inValue.Curreny_Code = Curreny_Code;
            inValue.Quantity = Quantity;
            inValue.Brand_ID = Brand_ID;
            inValue.Promotion_Code = Promotion_Code;
            Concentrator.Objects.RED.AddOrderItemRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).AddOrderItemRequest(inValue);
            return retVal.AddOrderItemRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.CompleteOrderReservationRequestResponse Concentrator.Objects.RED.RetailerSoap.CompleteOrderReservationRequest(Concentrator.Objects.RED.CompleteOrderReservationRequestRequest request) {
            return base.Channel.CompleteOrderReservationRequest(request);
        }
        
        public string CompleteOrderReservationRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Order_ID, string Reservation_Hold_Hours) {
            Concentrator.Objects.RED.CompleteOrderReservationRequestRequest inValue = new Concentrator.Objects.RED.CompleteOrderReservationRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Order_ID = Order_ID;
            inValue.Reservation_Hold_Hours = Reservation_Hold_Hours;
            Concentrator.Objects.RED.CompleteOrderReservationRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).CompleteOrderReservationRequest(inValue);
            return retVal.CompleteOrderReservationRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.OrderShipmentRequestResponse Concentrator.Objects.RED.RetailerSoap.OrderShipmentRequest(Concentrator.Objects.RED.OrderShipmentRequestRequest request) {
            return base.Channel.OrderShipmentRequest(request);
        }
        
        public string OrderShipmentRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Request_Xml) {
            Concentrator.Objects.RED.OrderShipmentRequestRequest inValue = new Concentrator.Objects.RED.OrderShipmentRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Request_Xml = Request_Xml;
            Concentrator.Objects.RED.OrderShipmentRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).OrderShipmentRequest(inValue);
            return retVal.OrderShipmentRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.CancelOrderReservationRequestResponse Concentrator.Objects.RED.RetailerSoap.CancelOrderReservationRequest(Concentrator.Objects.RED.CancelOrderReservationRequestRequest request) {
            return base.Channel.CancelOrderReservationRequest(request);
        }
        
        public string CancelOrderReservationRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Order_ID) {
            Concentrator.Objects.RED.CancelOrderReservationRequestRequest inValue = new Concentrator.Objects.RED.CancelOrderReservationRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Order_ID = Order_ID;
            Concentrator.Objects.RED.CancelOrderReservationRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).CancelOrderReservationRequest(inValue);
            return retVal.CancelOrderReservationRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.CommitToPurchaseOrderRequestResponse Concentrator.Objects.RED.RetailerSoap.CommitToPurchaseOrderRequest(Concentrator.Objects.RED.CommitToPurchaseOrderRequestRequest request) {
            return base.Channel.CommitToPurchaseOrderRequest(request);
        }
        
        public string CommitToPurchaseOrderRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Order_ID, string Purchase_Order_ID) {
            Concentrator.Objects.RED.CommitToPurchaseOrderRequestRequest inValue = new Concentrator.Objects.RED.CommitToPurchaseOrderRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Order_ID = Order_ID;
            inValue.Purchase_Order_ID = Purchase_Order_ID;
            Concentrator.Objects.RED.CommitToPurchaseOrderRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).CommitToPurchaseOrderRequest(inValue);
            return retVal.CommitToPurchaseOrderRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.PurchaseOrderItemFulfillmentRequestResponse Concentrator.Objects.RED.RetailerSoap.PurchaseOrderItemFulfillmentRequest(Concentrator.Objects.RED.PurchaseOrderItemFulfillmentRequestRequest request) {
            return base.Channel.PurchaseOrderItemFulfillmentRequest(request);
        }
        
        public string PurchaseOrderItemFulfillmentRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID, string Line_Item_ID, string Language_Code) {
            Concentrator.Objects.RED.PurchaseOrderItemFulfillmentRequestRequest inValue = new Concentrator.Objects.RED.PurchaseOrderItemFulfillmentRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Purchase_Order_ID = Purchase_Order_ID;
            inValue.Line_Item_ID = Line_Item_ID;
            inValue.Language_Code = Language_Code;
            Concentrator.Objects.RED.PurchaseOrderItemFulfillmentRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).PurchaseOrderItemFulfillmentRequest(inValue);
            return retVal.PurchaseOrderItemFulfillmentRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.PurchaseOrderItemFulfillmentDetailRequestResponse Concentrator.Objects.RED.RetailerSoap.PurchaseOrderItemFulfillmentDetailRequest(Concentrator.Objects.RED.PurchaseOrderItemFulfillmentDetailRequestRequest request) {
            return base.Channel.PurchaseOrderItemFulfillmentDetailRequest(request);
        }
        
        public string PurchaseOrderItemFulfillmentDetailRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID, string Line_Item_ID, string Language_Code) {
            Concentrator.Objects.RED.PurchaseOrderItemFulfillmentDetailRequestRequest inValue = new Concentrator.Objects.RED.PurchaseOrderItemFulfillmentDetailRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Purchase_Order_ID = Purchase_Order_ID;
            inValue.Line_Item_ID = Line_Item_ID;
            inValue.Language_Code = Language_Code;
            Concentrator.Objects.RED.PurchaseOrderItemFulfillmentDetailRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).PurchaseOrderItemFulfillmentDetailRequest(inValue);
            return retVal.PurchaseOrderItemFulfillmentDetailRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.SecurePackageToleranceAdjustmentRequestResponse Concentrator.Objects.RED.RetailerSoap.SecurePackageToleranceAdjustmentRequest(Concentrator.Objects.RED.SecurePackageToleranceAdjustmentRequestRequest request) {
            return base.Channel.SecurePackageToleranceAdjustmentRequest(request);
        }
        
        public string SecurePackageToleranceAdjustmentRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID, string Line_Item_ID, string Support_ID, int Unlock_Limit_Total) {
            Concentrator.Objects.RED.SecurePackageToleranceAdjustmentRequestRequest inValue = new Concentrator.Objects.RED.SecurePackageToleranceAdjustmentRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Purchase_Order_ID = Purchase_Order_ID;
            inValue.Line_Item_ID = Line_Item_ID;
            inValue.Support_ID = Support_ID;
            inValue.Unlock_Limit_Total = Unlock_Limit_Total;
            Concentrator.Objects.RED.SecurePackageToleranceAdjustmentRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).SecurePackageToleranceAdjustmentRequest(inValue);
            return retVal.SecurePackageToleranceAdjustmentRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.SerialNumberToleranceAdjustmentRequestResponse Concentrator.Objects.RED.RetailerSoap.SerialNumberToleranceAdjustmentRequest(Concentrator.Objects.RED.SerialNumberToleranceAdjustmentRequestRequest request) {
            return base.Channel.SerialNumberToleranceAdjustmentRequest(request);
        }
        
        public string SerialNumberToleranceAdjustmentRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID, string Line_Item_ID, string Serial_Number, string Support_ID, int Activation_Limit_Total) {
            Concentrator.Objects.RED.SerialNumberToleranceAdjustmentRequestRequest inValue = new Concentrator.Objects.RED.SerialNumberToleranceAdjustmentRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Purchase_Order_ID = Purchase_Order_ID;
            inValue.Line_Item_ID = Line_Item_ID;
            inValue.Serial_Number = Serial_Number;
            inValue.Support_ID = Support_ID;
            inValue.Activation_Limit_Total = Activation_Limit_Total;
            Concentrator.Objects.RED.SerialNumberToleranceAdjustmentRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).SerialNumberToleranceAdjustmentRequest(inValue);
            return retVal.SerialNumberToleranceAdjustmentRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.PurchaseOrderItemRefundRequestResponse Concentrator.Objects.RED.RetailerSoap.PurchaseOrderItemRefundRequest(Concentrator.Objects.RED.PurchaseOrderItemRefundRequestRequest request) {
            return base.Channel.PurchaseOrderItemRefundRequest(request);
        }
        
        public string PurchaseOrderItemRefundRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID, string Line_Item_ID) {
            Concentrator.Objects.RED.PurchaseOrderItemRefundRequestRequest inValue = new Concentrator.Objects.RED.PurchaseOrderItemRefundRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Purchase_Order_ID = Purchase_Order_ID;
            inValue.Line_Item_ID = Line_Item_ID;
            Concentrator.Objects.RED.PurchaseOrderItemRefundRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).PurchaseOrderItemRefundRequest(inValue);
            return retVal.PurchaseOrderItemRefundRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.PurchaseOrderChargebackRequestResponse Concentrator.Objects.RED.RetailerSoap.PurchaseOrderChargebackRequest(Concentrator.Objects.RED.PurchaseOrderChargebackRequestRequest request) {
            return base.Channel.PurchaseOrderChargebackRequest(request);
        }
        
        public string PurchaseOrderChargebackRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Purchase_Order_ID) {
            Concentrator.Objects.RED.PurchaseOrderChargebackRequestRequest inValue = new Concentrator.Objects.RED.PurchaseOrderChargebackRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Purchase_Order_ID = Purchase_Order_ID;
            Concentrator.Objects.RED.PurchaseOrderChargebackRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).PurchaseOrderChargebackRequest(inValue);
            return retVal.PurchaseOrderChargebackRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.GetCatalogUrlRequestResponse Concentrator.Objects.RED.RetailerSoap.GetCatalogUrlRequest(Concentrator.Objects.RED.GetCatalogUrlRequestRequest request) {
            return base.Channel.GetCatalogUrlRequest(request);
        }
        
        public string GetCatalogUrlRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Catalog_ID, string Catalog_Code) {
            Concentrator.Objects.RED.GetCatalogUrlRequestRequest inValue = new Concentrator.Objects.RED.GetCatalogUrlRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Catalog_ID = Catalog_ID;
            inValue.Catalog_Code = Catalog_Code;
            Concentrator.Objects.RED.GetCatalogUrlRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).GetCatalogUrlRequest(inValue);
            return retVal.GetCatalogUrlRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.CatalogResponseRequestResponse Concentrator.Objects.RED.RetailerSoap.CatalogResponseRequest(Concentrator.Objects.RED.CatalogResponseRequestRequest request) {
            return base.Channel.CatalogResponseRequest(request);
        }
        
        public string CatalogResponseRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Response_XML) {
            Concentrator.Objects.RED.CatalogResponseRequestRequest inValue = new Concentrator.Objects.RED.CatalogResponseRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Response_XML = Response_XML;
            Concentrator.Objects.RED.CatalogResponseRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).CatalogResponseRequest(inValue);
            return retVal.CatalogResponseRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.GetInvoiceBatchUrlRequestResponse Concentrator.Objects.RED.RetailerSoap.GetInvoiceBatchUrlRequest(Concentrator.Objects.RED.GetInvoiceBatchUrlRequestRequest request) {
            return base.Channel.GetInvoiceBatchUrlRequest(request);
        }
        
        public string GetInvoiceBatchUrlRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Batch_Control_Number) {
            Concentrator.Objects.RED.GetInvoiceBatchUrlRequestRequest inValue = new Concentrator.Objects.RED.GetInvoiceBatchUrlRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Batch_Control_Number = Batch_Control_Number;
            Concentrator.Objects.RED.GetInvoiceBatchUrlRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).GetInvoiceBatchUrlRequest(inValue);
            return retVal.GetInvoiceBatchUrlRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.InvoiceResponseRequestResponse Concentrator.Objects.RED.RetailerSoap.InvoiceResponseRequest(Concentrator.Objects.RED.InvoiceResponseRequestRequest request) {
            return base.Channel.InvoiceResponseRequest(request);
        }
        
        public string InvoiceResponseRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Invoice_Response_Xml) {
            Concentrator.Objects.RED.InvoiceResponseRequestRequest inValue = new Concentrator.Objects.RED.InvoiceResponseRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Invoice_Response_Xml = Invoice_Response_Xml;
            Concentrator.Objects.RED.InvoiceResponseRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).InvoiceResponseRequest(inValue);
            return retVal.InvoiceResponseRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Objects.RED.DigitalReceiptRequestResponse Concentrator.Objects.RED.RetailerSoap.DigitalReceiptRequest(Concentrator.Objects.RED.DigitalReceiptRequestRequest request) {
            return base.Channel.DigitalReceiptRequest(request);
        }
        
        public string DigitalReceiptRequest(Concentrator.Objects.RED.AuthenticationHeader AuthenticationHeader, string Support_ID, string Platform_ID, string Version_ID) {
            Concentrator.Objects.RED.DigitalReceiptRequestRequest inValue = new Concentrator.Objects.RED.DigitalReceiptRequestRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Support_ID = Support_ID;
            inValue.Platform_ID = Platform_ID;
            inValue.Version_ID = Version_ID;
            Concentrator.Objects.RED.DigitalReceiptRequestResponse retVal = ((Concentrator.Objects.RED.RetailerSoap)(this)).DigitalReceiptRequest(inValue);
            return retVal.DigitalReceiptRequestResult;
        }
    }
}
