//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concentrator.Plugins.PriceComparison.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\_Dennis\\SVN\\ScanImporter\\ScanImporter\\Schema\\Scan.xsd")]
        public string SchemaFile {
            get {
                return ((string)(this["SchemaFile"]));
            }
            set {
                this["SchemaFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\dennis\\Downloads\\competitorpricereport.xml")]
        public string XmlFile {
            get {
                return ((string)(this["XmlFile"]));
            }
            set {
                this["XmlFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\error.xml")]
        public string XmlLogFile {
            get {
                return ((string)(this["XmlLogFile"]));
            }
            set {
                this["XmlLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://secure.scan.co.uk/supplier/competitorpricexml.asp")]
        public string DownloadURL {
            get {
                return ((string)(this["DownloadURL"]));
            }
            set {
                this["DownloadURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("basxml")]
        public string WebUser {
            get {
                return ((string)(this["WebUser"]));
            }
            set {
                this["WebUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UDpQxd7VLb")]
        public string WebPass {
            get {
                return ((string)(this["WebPass"]));
            }
            set {
                this["WebPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EUR")]
        public string WebCurrency {
            get {
                return ((string)(this["WebCurrency"]));
            }
            set {
                this["WebCurrency"] = value;
            }
        }
    }
}
