//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concentrator.MiddleWare.TestConsole.ConcentratorContentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Concentrator.bascomputers.nl/", ConfigurationName="ConcentratorContentService.SpiderServiceSoap")]
    public interface SpiderServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetAssortment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Xml.XmlNode GetAssortment(int connectorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetAssortmentContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Xml.XmlNode GetAssortmentContent(int connectorID, bool importFullContent, bool singleProductGroup, bool shopInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetConcentratorProductInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Xml.XmlNode GetConcentratorProductInformation(int connectorID, bool importFullContent, bool singleProductGroup, int productID);
        
        // CODEGEN: Parameter 'LastUpdate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetAttributesAssortment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetAttributesAssortmentResponse GetAttributesAssortment(Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetAttributesAssortmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetZipcodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjectBaseOfZipCode))]
        ZipCode[] GetZipcodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetAssortmentImages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjectBaseOfZipCode))]
        System.Xml.XmlNode GetAssortmentImages(int connectorID);
        
        // CODEGEN: Parameter 'productID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetCustomImages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjectBaseOfZipCode))]
        Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetCustomImagesResponse GetCustomImages(Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetCustomImagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetFullSpiderContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjectBaseOfZipCode))]
        System.Xml.XmlNode GetFullSpiderContent(int connectorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetOAssortment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjectBaseOfZipCode))]
        System.Xml.XmlNode GetOAssortment(int connectorID, bool costPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetProductInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjectBaseOfZipCode))]
        System.Xml.XmlNode GetProductInformation(int connectorID, string customItemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetProductsInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjectBaseOfZipCode))]
        System.Xml.XmlNode GetProductsInformation(ProductInformation[] products, int vendorID, int connectorID, int language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetProductReviews", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjectBaseOfZipCode))]
        System.Xml.XmlNode GetProductReviews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Concentrator.bascomputers.nl/GetExpertProductReviews", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjectBaseOfZipCode))]
        string GetExpertProductReviews();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttributesAssortment", WrapperNamespace="http://Concentrator.bascomputers.nl/", IsWrapped=true)]
    public partial class GetAttributesAssortmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Concentrator.bascomputers.nl/", Order=0)]
        public int connectorID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Concentrator.bascomputers.nl/", Order=1)]
        public int[] ProductIDs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Concentrator.bascomputers.nl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastUpdate;
        
        public GetAttributesAssortmentRequest() {
        }
        
        public GetAttributesAssortmentRequest(int connectorID, int[] ProductIDs, System.Nullable<System.DateTime> LastUpdate) {
            this.connectorID = connectorID;
            this.ProductIDs = ProductIDs;
            this.LastUpdate = LastUpdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttributesAssortmentResponse", WrapperNamespace="http://Concentrator.bascomputers.nl/", IsWrapped=true)]
    public partial class GetAttributesAssortmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Concentrator.bascomputers.nl/", Order=0)]
        public string GetAttributesAssortmentResult;
        
        public GetAttributesAssortmentResponse() {
        }
        
        public GetAttributesAssortmentResponse(string GetAttributesAssortmentResult) {
            this.GetAttributesAssortmentResult = GetAttributesAssortmentResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Concentrator.bascomputers.nl/")]
    public partial class ZipCode : ObjectBaseOfZipCode {
        
        private int zipCodeIDField;
        
        private string pCWIJKField;
        
        private string pCLETTERField;
        
        private string pCREEKSIDField;
        
        private int pCREEKSVANField;
        
        private int pCREEKSTOTField;
        
        private string pCCITYTPGField;
        
        private string pCCITYNENField;
        
        private string pCSTRTPGField;
        
        private string pCSTRNENField;
        
        private string pCSTROFFField;
        
        private string pCCITYEXTField;
        
        private string pCSTREXTField;
        
        private int pCGEMEENTEIDField;
        
        private string pCGEMEENTENAAMField;
        
        private string pCPROVINCIEField;
        
        private int pCCEBUCOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ZipCodeID {
            get {
                return this.zipCodeIDField;
            }
            set {
                this.zipCodeIDField = value;
                this.RaisePropertyChanged("ZipCodeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PCWIJK {
            get {
                return this.pCWIJKField;
            }
            set {
                this.pCWIJKField = value;
                this.RaisePropertyChanged("PCWIJK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PCLETTER {
            get {
                return this.pCLETTERField;
            }
            set {
                this.pCLETTERField = value;
                this.RaisePropertyChanged("PCLETTER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PCREEKSID {
            get {
                return this.pCREEKSIDField;
            }
            set {
                this.pCREEKSIDField = value;
                this.RaisePropertyChanged("PCREEKSID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PCREEKSVAN {
            get {
                return this.pCREEKSVANField;
            }
            set {
                this.pCREEKSVANField = value;
                this.RaisePropertyChanged("PCREEKSVAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int PCREEKSTOT {
            get {
                return this.pCREEKSTOTField;
            }
            set {
                this.pCREEKSTOTField = value;
                this.RaisePropertyChanged("PCREEKSTOT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PCCITYTPG {
            get {
                return this.pCCITYTPGField;
            }
            set {
                this.pCCITYTPGField = value;
                this.RaisePropertyChanged("PCCITYTPG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PCCITYNEN {
            get {
                return this.pCCITYNENField;
            }
            set {
                this.pCCITYNENField = value;
                this.RaisePropertyChanged("PCCITYNEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PCSTRTPG {
            get {
                return this.pCSTRTPGField;
            }
            set {
                this.pCSTRTPGField = value;
                this.RaisePropertyChanged("PCSTRTPG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PCSTRNEN {
            get {
                return this.pCSTRNENField;
            }
            set {
                this.pCSTRNENField = value;
                this.RaisePropertyChanged("PCSTRNEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PCSTROFF {
            get {
                return this.pCSTROFFField;
            }
            set {
                this.pCSTROFFField = value;
                this.RaisePropertyChanged("PCSTROFF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PCCITYEXT {
            get {
                return this.pCCITYEXTField;
            }
            set {
                this.pCCITYEXTField = value;
                this.RaisePropertyChanged("PCCITYEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PCSTREXT {
            get {
                return this.pCSTREXTField;
            }
            set {
                this.pCSTREXTField = value;
                this.RaisePropertyChanged("PCSTREXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int PCGEMEENTEID {
            get {
                return this.pCGEMEENTEIDField;
            }
            set {
                this.pCGEMEENTEIDField = value;
                this.RaisePropertyChanged("PCGEMEENTEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PCGEMEENTENAAM {
            get {
                return this.pCGEMEENTENAAMField;
            }
            set {
                this.pCGEMEENTENAAMField = value;
                this.RaisePropertyChanged("PCGEMEENTENAAM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PCPROVINCIE {
            get {
                return this.pCPROVINCIEField;
            }
            set {
                this.pCPROVINCIEField = value;
                this.RaisePropertyChanged("PCPROVINCIE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int PCCEBUCO {
            get {
                return this.pCCEBUCOField;
            }
            set {
                this.pCCEBUCOField = value;
                this.RaisePropertyChanged("PCCEBUCO");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZipCode))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Concentrator.bascomputers.nl/")]
    public abstract partial class ObjectBaseOfZipCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Concentrator.bascomputers.nl/")]
    public partial class ProductInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int customProductIDField;
        
        private string brandCodeField;
        
        private string parentProductGroupCodeField;
        
        private string productGroupCodeField;
        
        private string brandnameField;
        
        private string parentProductGroupNameField;
        
        private string productGroupNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CustomProductID {
            get {
                return this.customProductIDField;
            }
            set {
                this.customProductIDField = value;
                this.RaisePropertyChanged("CustomProductID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BrandCode {
            get {
                return this.brandCodeField;
            }
            set {
                this.brandCodeField = value;
                this.RaisePropertyChanged("BrandCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ParentProductGroupCode {
            get {
                return this.parentProductGroupCodeField;
            }
            set {
                this.parentProductGroupCodeField = value;
                this.RaisePropertyChanged("ParentProductGroupCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProductGroupCode {
            get {
                return this.productGroupCodeField;
            }
            set {
                this.productGroupCodeField = value;
                this.RaisePropertyChanged("ProductGroupCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Brandname {
            get {
                return this.brandnameField;
            }
            set {
                this.brandnameField = value;
                this.RaisePropertyChanged("Brandname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ParentProductGroupName {
            get {
                return this.parentProductGroupNameField;
            }
            set {
                this.parentProductGroupNameField = value;
                this.RaisePropertyChanged("ParentProductGroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ProductGroupName {
            get {
                return this.productGroupNameField;
            }
            set {
                this.productGroupNameField = value;
                this.RaisePropertyChanged("ProductGroupName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomImages", WrapperNamespace="http://Concentrator.bascomputers.nl/", IsWrapped=true)]
    public partial class GetCustomImagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Concentrator.bascomputers.nl/", Order=0)]
        public string manufacturerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Concentrator.bascomputers.nl/", Order=1)]
        public int connectorID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Concentrator.bascomputers.nl/", Order=2)]
        public string brandCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Concentrator.bascomputers.nl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> productID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Concentrator.bascomputers.nl/", Order=4)]
        public string customItemNumber;
        
        public GetCustomImagesRequest() {
        }
        
        public GetCustomImagesRequest(string manufacturerID, int connectorID, string brandCode, System.Nullable<int> productID, string customItemNumber) {
            this.manufacturerID = manufacturerID;
            this.connectorID = connectorID;
            this.brandCode = brandCode;
            this.productID = productID;
            this.customItemNumber = customItemNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomImagesResponse", WrapperNamespace="http://Concentrator.bascomputers.nl/", IsWrapped=true)]
    public partial class GetCustomImagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Concentrator.bascomputers.nl/", Order=0)]
        public System.Xml.XmlNode GetCustomImagesResult;
        
        public GetCustomImagesResponse() {
        }
        
        public GetCustomImagesResponse(System.Xml.XmlNode GetCustomImagesResult) {
            this.GetCustomImagesResult = GetCustomImagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SpiderServiceSoapChannel : Concentrator.MiddleWare.TestConsole.ConcentratorContentService.SpiderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SpiderServiceSoapClient : System.ServiceModel.ClientBase<Concentrator.MiddleWare.TestConsole.ConcentratorContentService.SpiderServiceSoap>, Concentrator.MiddleWare.TestConsole.ConcentratorContentService.SpiderServiceSoap {
        
        public SpiderServiceSoapClient() {
        }
        
        public SpiderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpiderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpiderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpiderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode GetAssortment(int connectorID) {
            return base.Channel.GetAssortment(connectorID);
        }
        
        public System.Xml.XmlNode GetAssortmentContent(int connectorID, bool importFullContent, bool singleProductGroup, bool shopInformation) {
            return base.Channel.GetAssortmentContent(connectorID, importFullContent, singleProductGroup, shopInformation);
        }
        
        public System.Xml.XmlNode GetConcentratorProductInformation(int connectorID, bool importFullContent, bool singleProductGroup, int productID) {
            return base.Channel.GetConcentratorProductInformation(connectorID, importFullContent, singleProductGroup, productID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetAttributesAssortmentResponse Concentrator.MiddleWare.TestConsole.ConcentratorContentService.SpiderServiceSoap.GetAttributesAssortment(Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetAttributesAssortmentRequest request) {
            return base.Channel.GetAttributesAssortment(request);
        }
        
        public string GetAttributesAssortment(int connectorID, int[] ProductIDs, System.Nullable<System.DateTime> LastUpdate) {
            Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetAttributesAssortmentRequest inValue = new Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetAttributesAssortmentRequest();
            inValue.connectorID = connectorID;
            inValue.ProductIDs = ProductIDs;
            inValue.LastUpdate = LastUpdate;
            Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetAttributesAssortmentResponse retVal = ((Concentrator.MiddleWare.TestConsole.ConcentratorContentService.SpiderServiceSoap)(this)).GetAttributesAssortment(inValue);
            return retVal.GetAttributesAssortmentResult;
        }
        
        public ZipCode[] GetZipcodes() {
            return base.Channel.GetZipcodes();
        }
        
        public System.Xml.XmlNode GetAssortmentImages(int connectorID) {
            return base.Channel.GetAssortmentImages(connectorID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetCustomImagesResponse Concentrator.MiddleWare.TestConsole.ConcentratorContentService.SpiderServiceSoap.GetCustomImages(Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetCustomImagesRequest request) {
            return base.Channel.GetCustomImages(request);
        }
        
        public System.Xml.XmlNode GetCustomImages(string manufacturerID, int connectorID, string brandCode, System.Nullable<int> productID, string customItemNumber) {
            Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetCustomImagesRequest inValue = new Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetCustomImagesRequest();
            inValue.manufacturerID = manufacturerID;
            inValue.connectorID = connectorID;
            inValue.brandCode = brandCode;
            inValue.productID = productID;
            inValue.customItemNumber = customItemNumber;
            Concentrator.MiddleWare.TestConsole.ConcentratorContentService.GetCustomImagesResponse retVal = ((Concentrator.MiddleWare.TestConsole.ConcentratorContentService.SpiderServiceSoap)(this)).GetCustomImages(inValue);
            return retVal.GetCustomImagesResult;
        }
        
        public System.Xml.XmlNode GetFullSpiderContent(int connectorID) {
            return base.Channel.GetFullSpiderContent(connectorID);
        }
        
        public System.Xml.XmlNode GetOAssortment(int connectorID, bool costPrice) {
            return base.Channel.GetOAssortment(connectorID, costPrice);
        }
        
        public System.Xml.XmlNode GetProductInformation(int connectorID, string customItemNumber) {
            return base.Channel.GetProductInformation(connectorID, customItemNumber);
        }
        
        public System.Xml.XmlNode GetProductsInformation(ProductInformation[] products, int vendorID, int connectorID, int language) {
            return base.Channel.GetProductsInformation(products, vendorID, connectorID, language);
        }
        
        public System.Xml.XmlNode GetProductReviews() {
            return base.Channel.GetProductReviews();
        }
        
        public string GetExpertProductReviews() {
            return base.Channel.GetExpertProductReviews();
        }
    }
}
