//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concentrator.Web.ServiceClient.ZipCodeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZipCodeService.ZipCodesSoap")]
    public interface ZipCodesSoap {
        
        // CODEGEN: Generating message contract since element name GetZipcodesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZipcodes", ReplyAction="*")]
        Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesResponse GetZipcodes(Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZipcodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZipcodes", Namespace="http://tempuri.org/", Order=0)]
        public Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesRequestBody Body;
        
        public GetZipcodesRequest() {
        }
        
        public GetZipcodesRequest(Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetZipcodesRequestBody {
        
        public GetZipcodesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZipcodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZipcodesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesResponseBody Body;
        
        public GetZipcodesResponse() {
        }
        
        public GetZipcodesResponse(Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetZipcodesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetZipcodesResult;
        
        public GetZipcodesResponseBody() {
        }
        
        public GetZipcodesResponseBody(byte[] GetZipcodesResult) {
            this.GetZipcodesResult = GetZipcodesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZipCodesSoapChannel : Concentrator.Web.ServiceClient.ZipCodeService.ZipCodesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZipCodesSoapClient : System.ServiceModel.ClientBase<Concentrator.Web.ServiceClient.ZipCodeService.ZipCodesSoap>, Concentrator.Web.ServiceClient.ZipCodeService.ZipCodesSoap {
        
        public ZipCodesSoapClient() {
        }
        
        public ZipCodesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZipCodesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipCodesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipCodesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesResponse Concentrator.Web.ServiceClient.ZipCodeService.ZipCodesSoap.GetZipcodes(Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesRequest request) {
            return base.Channel.GetZipcodes(request);
        }
        
        public byte[] GetZipcodes() {
            Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesRequest inValue = new Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesRequest();
            inValue.Body = new Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesRequestBody();
            Concentrator.Web.ServiceClient.ZipCodeService.GetZipcodesResponse retVal = ((Concentrator.Web.ServiceClient.ZipCodeService.ZipCodesSoap)(this)).GetZipcodes(inValue);
            return retVal.Body.GetZipcodesResult;
        }
    }
}
