#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concentrator.Vendors.IceCat
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ICECAT")]
	public partial class ICEcatDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdt_SummaryDescription(dt_SummaryDescription instance);
    partial void Updatedt_SummaryDescription(dt_SummaryDescription instance);
    partial void Deletedt_SummaryDescription(dt_SummaryDescription instance);
    partial void Insertdt_Product(dt_Product instance);
    partial void Updatedt_Product(dt_Product instance);
    partial void Deletedt_Product(dt_Product instance);
    partial void Insertdt_ProductDescription(dt_ProductDescription instance);
    partial void Updatedt_ProductDescription(dt_ProductDescription instance);
    partial void Deletedt_ProductDescription(dt_ProductDescription instance);
    partial void Insertdt_ProductRelated(dt_ProductRelated instance);
    partial void Updatedt_ProductRelated(dt_ProductRelated instance);
    partial void Deletedt_ProductRelated(dt_ProductRelated instance);
    #endregion
		
		public ICEcatDataContext() : 
				base(global::Concentrator.Vendors.IceCat.Properties.Settings.Default.ICECATConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public ICEcatDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ICEcatDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ICEcatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ICEcatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dt_Feature> dt_Features
		{
			get
			{
				return this.GetTable<dt_Feature>();
			}
		}
		
		public System.Data.Linq.Table<dt_Measure> dt_Measures
		{
			get
			{
				return this.GetTable<dt_Measure>();
			}
		}
		
		public System.Data.Linq.Table<Brands> Brands
		{
			get
			{
				return this.GetTable<Brands>();
			}
		}
		
		public System.Data.Linq.Table<dt_Name> dt_Names
		{
			get
			{
				return this.GetTable<dt_Name>();
			}
		}
		
		public System.Data.Linq.Table<dt_Productfeature> dt_Productfeatures
		{
			get
			{
				return this.GetTable<dt_Productfeature>();
			}
		}
		
		public System.Data.Linq.Table<CategoryList> CategoryLists
		{
			get
			{
				return this.GetTable<CategoryList>();
			}
		}
		
		public System.Data.Linq.Table<CategoryNames> CategoryNames
		{
			get
			{
				return this.GetTable<CategoryNames>();
			}
		}
		
		public System.Data.Linq.Table<ParentCategory> ParentCategories
		{
			get
			{
				return this.GetTable<ParentCategory>();
			}
		}
		
		public System.Data.Linq.Table<dt_SummaryDescription> dt_SummaryDescriptions
		{
			get
			{
				return this.GetTable<dt_SummaryDescription>();
			}
		}
		
		public System.Data.Linq.Table<dt_Product> dt_Products
		{
			get
			{
				return this.GetTable<dt_Product>();
			}
		}
		
		public System.Data.Linq.Table<dt_ProductDescription> dt_ProductDescriptions
		{
			get
			{
				return this.GetTable<dt_ProductDescription>();
			}
		}
		
		public System.Data.Linq.Table<dt_ProductRelated> dt_ProductRelateds
		{
			get
			{
				return this.GetTable<dt_ProductRelated>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Concentrator_GetIceProductAttributebyManufactID")]
		public ISingleResult<Concentrator_GetIceProductAttributebyManufactIDResult> Concentrator_GetIceProductAttributebyManufactID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ManufactID", DbType="VarChar(50)")] string manufactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierID", DbType="Int")] System.Nullable<int> supplierID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageID", DbType="Int")] System.Nullable<int> languageID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manufactID, supplierID, languageID);
			return ((ISingleResult<Concentrator_GetIceProductAttributebyManufactIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Concentrator_GetIceProductAttributes")]
		public ISingleResult<Concentrator_GetIceProductAttributesResult> Concentrator_GetIceProductAttributes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Products", DbType="Xml")] System.Xml.Linq.XElement products, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageID", DbType="Int")] System.Nullable<int> languageID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Updates", DbType="BigInt")] System.Nullable<long> updates)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), products, languageID, updates);
			return ((ISingleResult<Concentrator_GetIceProductAttributesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Concentrator_GetIceCatAttribute")]
		public ISingleResult<Concentrator_GetIceCatAttributeResult> Concentrator_GetIceCatAttribute([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ManufactID", DbType="VarChar(50)")] string manufactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierID", DbType="Int")] System.Nullable<int> supplierID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageID", DbType="Int")] System.Nullable<int> languageID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manufactID, supplierID, languageID);
			return ((ISingleResult<Concentrator_GetIceCatAttributeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Concentrator_GetIceProductbyManufactID")]
		public ISingleResult<Concentrator_GetIceProductbyManufactIDResult> Concentrator_GetIceProductbyManufactID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ManufactID", DbType="VarChar(50)")] string manufactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierID", DbType="Int")] System.Nullable<int> supplierID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageID", DbType="Int")] System.Nullable<int> languageID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manufactID, supplierID, languageID);
			return ((ISingleResult<Concentrator_GetIceProductbyManufactIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Concentrator_GetIceProductFullbyManufactID")]
		public ISingleResult<Concentrator_GetIceProductFullbyManufactIDResult> Concentrator_GetIceProductFullbyManufactID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ManufactID", DbType="VarChar(50)")] string manufactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierID", DbType="Int")] System.Nullable<int> supplierID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageID", DbType="Int")] System.Nullable<int> languageID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manufactID, supplierID, languageID);
			return ((ISingleResult<Concentrator_GetIceProductFullbyManufactIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Concentrator_GetIceProductCategories")]
		public ISingleResult<Concentrator_GetIceProductCategoriesResult> Concentrator_GetIceProductCategories([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Products", DbType="Xml")] System.Xml.Linq.XElement products, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageID", DbType="Int")] System.Nullable<int> languageID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), products, languageID);
			return ((ISingleResult<Concentrator_GetIceProductCategoriesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Concentrator_GetIceCategory")]
		public ISingleResult<Concentrator_GetIceCategoryResult> Concentrator_GetIceCategory([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ManufactID", DbType="VarChar(50)")] string manufactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierID", DbType="Int")] System.Nullable<int> supplierID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageID", DbType="Int")] System.Nullable<int> languageID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manufactID, supplierID, languageID);
			return ((ISingleResult<Concentrator_GetIceCategoryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Concentrator_GetIceProductDescriptions")]
		public ISingleResult<Concentrator_GetIceProductDescriptionsResult> Concentrator_GetIceProductDescriptions([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string vendorItemNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> supplier_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vendorItemNumber, supplier_id);
			return ((ISingleResult<Concentrator_GetIceProductDescriptionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Concentrator_GetIceProductImageUrlbyICEcatID")]
		public ISingleResult<Concentrator_GetIceProductImageUrlbyICEcatIDResult> Concentrator_GetIceProductImageUrlbyICEcatID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ManufactID", DbType="VarChar(50)")] string manufactID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplierID", DbType="Int")] System.Nullable<int> supplierID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductGroupID", DbType="Int")] System.Nullable<int> productGroupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> langid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manufactID, supplierID, productGroupID, langid);
			return ((ISingleResult<Concentrator_GetIceProductImageUrlbyICEcatIDResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_Feature")]
	public partial class dt_Feature
	{
		
		private System.Nullable<double> _ProductFeature_ID;
		
		private System.Nullable<double> _Feature_ID;
		
		private string _langid;
		
		public dt_Feature()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductFeature_ID", DbType="Float")]
		public System.Nullable<double> ProductFeature_ID
		{
			get
			{
				return this._ProductFeature_ID;
			}
			set
			{
				if ((this._ProductFeature_ID != value))
				{
					this._ProductFeature_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Feature_ID", DbType="Float")]
		public System.Nullable<double> Feature_ID
		{
			get
			{
				return this._Feature_ID;
			}
			set
			{
				if ((this._Feature_ID != value))
				{
					this._Feature_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_langid", DbType="NVarChar(50)")]
		public string langid
		{
			get
			{
				return this._langid;
			}
			set
			{
				if ((this._langid != value))
				{
					this._langid = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_Measure")]
	public partial class dt_Measure
	{
		
		private System.Nullable<double> _Feature_ID;
		
		private string _Measure_ID;
		
		private string _Sign;
		
		public dt_Measure()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Feature_ID", DbType="Float")]
		public System.Nullable<double> Feature_ID
		{
			get
			{
				return this._Feature_ID;
			}
			set
			{
				if ((this._Feature_ID != value))
				{
					this._Feature_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Measure_ID", DbType="NVarChar(50)")]
		public string Measure_ID
		{
			get
			{
				return this._Measure_ID;
			}
			set
			{
				if ((this._Measure_ID != value))
				{
					this._Measure_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sign", DbType="NVarChar(50)")]
		public string Sign
		{
			get
			{
				return this._Sign;
			}
			set
			{
				if ((this._Sign != value))
				{
					this._Sign = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_Supplier")]
	public partial class Brands
	{
		
		private System.Nullable<int> _Product_ID;
		
		private double _Supplier_ID;
		
		private string _Supplier_Name;
		
		public Brands()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Int NULL")]
		public System.Nullable<int> Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this._Product_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_ID", DbType="Float NOT NULL")]
		public double Supplier_ID
		{
			get
			{
				return this._Supplier_ID;
			}
			set
			{
				if ((this._Supplier_ID != value))
				{
					this._Supplier_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_Name", DbType="NVarChar(50)")]
		public string Supplier_Name
		{
			get
			{
				return this._Supplier_Name;
			}
			set
			{
				if ((this._Supplier_Name != value))
				{
					this._Supplier_Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_Name")]
	public partial class dt_Name
	{
		
		private System.Nullable<double> _Feature_ID;
		
		private System.Nullable<double> _Name_ID;
		
		private string _Value;
		
		private string _langid;
		
		public dt_Name()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Feature_ID", DbType="Float")]
		public System.Nullable<double> Feature_ID
		{
			get
			{
				return this._Feature_ID;
			}
			set
			{
				if ((this._Feature_ID != value))
				{
					this._Feature_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_ID", DbType="Float")]
		public System.Nullable<double> Name_ID
		{
			get
			{
				return this._Name_ID;
			}
			set
			{
				if ((this._Name_ID != value))
				{
					this._Name_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(150)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_langid", DbType="NVarChar(50)")]
		public string langid
		{
			get
			{
				return this._langid;
			}
			set
			{
				if ((this._langid != value))
				{
					this._langid = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_Productfeature")]
	public partial class dt_Productfeature
	{
		
		private System.Nullable<int> _Product_ID;
		
		private System.Nullable<double> _ProductFeature_ID;
		
		private string _Localized;
		
		private string _Value;
		
		private System.Nullable<double> _CategoryFeature_ID;
		
		private System.Nullable<double> _CategoryFeatureGroup_ID;
		
		private string _No;
		
		private string _Presentation_Value;
		
		public dt_Productfeature()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="INT NULL")]
		public System.Nullable<int> Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this._Product_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductFeature_ID", DbType="Float")]
		public System.Nullable<double> ProductFeature_ID
		{
			get
			{
				return this._ProductFeature_ID;
			}
			set
			{
				if ((this._ProductFeature_ID != value))
				{
					this._ProductFeature_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localized", DbType="NVarChar(50)")]
		public string Localized
		{
			get
			{
				return this._Localized;
			}
			set
			{
				if ((this._Localized != value))
				{
					this._Localized = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="VarChar(6000)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryFeature_ID", DbType="Float")]
		public System.Nullable<double> CategoryFeature_ID
		{
			get
			{
				return this._CategoryFeature_ID;
			}
			set
			{
				if ((this._CategoryFeature_ID != value))
				{
					this._CategoryFeature_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryFeatureGroup_ID", DbType="Float")]
		public System.Nullable<double> CategoryFeatureGroup_ID
		{
			get
			{
				return this._CategoryFeatureGroup_ID;
			}
			set
			{
				if ((this._CategoryFeatureGroup_ID != value))
				{
					this._CategoryFeatureGroup_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="NVarChar(50)")]
		public string No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this._No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Presentation_Value", DbType="VarChar(7000)")]
		public string Presentation_Value
		{
			get
			{
				return this._Presentation_Value;
			}
			set
			{
				if ((this._Presentation_Value != value))
				{
					this._Presentation_Value = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CategoryList")]
	public partial class CategoryList
	{
		
		private System.Nullable<int> _ID;
		
		private string _UNCATID;
		
		private string _Searchable;
		
		private string _ThumbPic;
		
		private string _Score;
		
		private string _LowPic;
		
		public CategoryList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="INT NULL")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNCATID", DbType="NVarChar(53)")]
		public string UNCATID
		{
			get
			{
				return this._UNCATID;
			}
			set
			{
				if ((this._UNCATID != value))
				{
					this._UNCATID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Searchable", DbType="NVarChar(50)")]
		public string Searchable
		{
			get
			{
				return this._Searchable;
			}
			set
			{
				if ((this._Searchable != value))
				{
					this._Searchable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbPic", DbType="NVarChar(150)")]
		public string ThumbPic
		{
			get
			{
				return this._ThumbPic;
			}
			set
			{
				if ((this._ThumbPic != value))
				{
					this._ThumbPic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="NVarChar(53)")]
		public string Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this._Score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPic", DbType="NVarChar(150)")]
		public string LowPic
		{
			get
			{
				return this._LowPic;
			}
			set
			{
				if ((this._LowPic != value))
				{
					this._LowPic = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CategoryNames")]
	public partial class CategoryNames
	{
		
		private System.Nullable<int> _Cat_ID;
		
		private string _Name_ID;
		
		private string _langid;
		
		private string _CategoryName;
		
		public CategoryNames()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_ID", DbType="INT NULL")]
		public System.Nullable<int> Cat_ID
		{
			get
			{
				return this._Cat_ID;
			}
			set
			{
				if ((this._Cat_ID != value))
				{
					this._Cat_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_ID", DbType="NVarChar(53)")]
		public string Name_ID
		{
			get
			{
				return this._Name_ID;
			}
			set
			{
				if ((this._Name_ID != value))
				{
					this._Name_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_langid", DbType="NVarChar(50)")]
		public string langid
		{
			get
			{
				return this._langid;
			}
			set
			{
				if ((this._langid != value))
				{
					this._langid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(1500)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ParentCategory")]
	public partial class ParentCategory
	{
		
		private System.Nullable<int> _Cat_ID;
		
		private string _Parent_ID;
		
		public ParentCategory()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_ID", DbType="Int NULL")]
		public System.Nullable<int> Cat_ID
		{
			get
			{
				return this._Cat_ID;
			}
			set
			{
				if ((this._Cat_ID != value))
				{
					this._Cat_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_ID", DbType="NVarChar(53)")]
		public string Parent_ID
		{
			get
			{
				return this._Parent_ID;
			}
			set
			{
				if ((this._Parent_ID != value))
				{
					this._Parent_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_SummaryDescription")]
	public partial class dt_SummaryDescription : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _Product_ID;
		
		private string _ShortSummaryDescription;
		
		private string _LongSummaryDescription;
		
		private string _Langid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduct_IDChanging(double value);
    partial void OnProduct_IDChanged();
    partial void OnShortSummaryDescriptionChanging(string value);
    partial void OnShortSummaryDescriptionChanged();
    partial void OnLongSummaryDescriptionChanging(string value);
    partial void OnLongSummaryDescriptionChanged();
    partial void OnLangidChanging(string value);
    partial void OnLangidChanged();
    #endregion
		
		public dt_SummaryDescription()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this.OnProduct_IDChanging(value);
					this.SendPropertyChanging();
					this._Product_ID = value;
					this.SendPropertyChanged("Product_ID");
					this.OnProduct_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortSummaryDescription", DbType="NVarChar(750)")]
		public string ShortSummaryDescription
		{
			get
			{
				return this._ShortSummaryDescription;
			}
			set
			{
				if ((this._ShortSummaryDescription != value))
				{
					this.OnShortSummaryDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ShortSummaryDescription = value;
					this.SendPropertyChanged("ShortSummaryDescription");
					this.OnShortSummaryDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongSummaryDescription", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LongSummaryDescription
		{
			get
			{
				return this._LongSummaryDescription;
			}
			set
			{
				if ((this._LongSummaryDescription != value))
				{
					this.OnLongSummaryDescriptionChanging(value);
					this.SendPropertyChanging();
					this._LongSummaryDescription = value;
					this.SendPropertyChanged("LongSummaryDescription");
					this.OnLongSummaryDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Langid", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Langid
		{
			get
			{
				return this._Langid;
			}
			set
			{
				if ((this._Langid != value))
				{
					this.OnLangidChanging(value);
					this.SendPropertyChanging();
					this._Langid = value;
					this.SendPropertyChanged("Langid");
					this.OnLangidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_Product")]
	public partial class dt_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Product_ID;
		
		private System.Nullable<double> _ThumbPicSize;
		
		private string _Quality;
		
		private string _HighPic;
		
		private string _LowPic;
		
		private System.Nullable<double> _LowPicSize;
		
		private string _Prod_ID;
		
		private System.Nullable<double> _HighPicSize;
		
		private string _ThumbPic;
		
		private string _Code;
		
		private string _Name;
		
		private string _Langid;
		
		private string _Updated;
		
		private string _ModelName;
		
		private int _Supplier_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduct_IDChanging(int value);
    partial void OnProduct_IDChanged();
    partial void OnThumbPicSizeChanging(System.Nullable<double> value);
    partial void OnThumbPicSizeChanged();
    partial void OnQualityChanging(string value);
    partial void OnQualityChanged();
    partial void OnHighPicChanging(string value);
    partial void OnHighPicChanged();
    partial void OnLowPicChanging(string value);
    partial void OnLowPicChanged();
    partial void OnLowPicSizeChanging(System.Nullable<double> value);
    partial void OnLowPicSizeChanged();
    partial void OnProd_IDChanging(string value);
    partial void OnProd_IDChanged();
    partial void OnHighPicSizeChanging(System.Nullable<double> value);
    partial void OnHighPicSizeChanged();
    partial void OnThumbPicChanging(string value);
    partial void OnThumbPicChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnLangidChanging(string value);
    partial void OnLangidChanged();
    partial void OnUpdatedChanging(string value);
    partial void OnUpdatedChanged();
    partial void OnModelNameChanging(string value);
    partial void OnModelNameChanged();
    partial void OnSupplier_idChanging(int value);
    partial void OnSupplier_idChanged();
    #endregion
		
		public dt_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this.OnProduct_IDChanging(value);
					this.SendPropertyChanging();
					this._Product_ID = value;
					this.SendPropertyChanged("Product_ID");
					this.OnProduct_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbPicSize", DbType="Float")]
		public System.Nullable<double> ThumbPicSize
		{
			get
			{
				return this._ThumbPicSize;
			}
			set
			{
				if ((this._ThumbPicSize != value))
				{
					this.OnThumbPicSizeChanging(value);
					this.SendPropertyChanging();
					this._ThumbPicSize = value;
					this.SendPropertyChanged("ThumbPicSize");
					this.OnThumbPicSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quality", DbType="NVarChar(50)")]
		public string Quality
		{
			get
			{
				return this._Quality;
			}
			set
			{
				if ((this._Quality != value))
				{
					this.OnQualityChanging(value);
					this.SendPropertyChanging();
					this._Quality = value;
					this.SendPropertyChanged("Quality");
					this.OnQualityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighPic", DbType="NVarChar(100)")]
		public string HighPic
		{
			get
			{
				return this._HighPic;
			}
			set
			{
				if ((this._HighPic != value))
				{
					this.OnHighPicChanging(value);
					this.SendPropertyChanging();
					this._HighPic = value;
					this.SendPropertyChanged("HighPic");
					this.OnHighPicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPic", DbType="NVarChar(100)")]
		public string LowPic
		{
			get
			{
				return this._LowPic;
			}
			set
			{
				if ((this._LowPic != value))
				{
					this.OnLowPicChanging(value);
					this.SendPropertyChanging();
					this._LowPic = value;
					this.SendPropertyChanged("LowPic");
					this.OnLowPicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPicSize", DbType="Float")]
		public System.Nullable<double> LowPicSize
		{
			get
			{
				return this._LowPicSize;
			}
			set
			{
				if ((this._LowPicSize != value))
				{
					this.OnLowPicSizeChanging(value);
					this.SendPropertyChanging();
					this._LowPicSize = value;
					this.SendPropertyChanged("LowPicSize");
					this.OnLowPicSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_ID", DbType="NVarChar(75)")]
		public string Prod_ID
		{
			get
			{
				return this._Prod_ID;
			}
			set
			{
				if ((this._Prod_ID != value))
				{
					this.OnProd_IDChanging(value);
					this.SendPropertyChanging();
					this._Prod_ID = value;
					this.SendPropertyChanged("Prod_ID");
					this.OnProd_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighPicSize", DbType="Float")]
		public System.Nullable<double> HighPicSize
		{
			get
			{
				return this._HighPicSize;
			}
			set
			{
				if ((this._HighPicSize != value))
				{
					this.OnHighPicSizeChanging(value);
					this.SendPropertyChanging();
					this._HighPicSize = value;
					this.SendPropertyChanged("HighPicSize");
					this.OnHighPicSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbPic", DbType="NVarChar(75)")]
		public string ThumbPic
		{
			get
			{
				return this._ThumbPic;
			}
			set
			{
				if ((this._ThumbPic != value))
				{
					this.OnThumbPicChanging(value);
					this.SendPropertyChanging();
					this._ThumbPic = value;
					this.SendPropertyChanged("ThumbPic");
					this.OnThumbPicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(175)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Langid", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Langid
		{
			get
			{
				return this._Langid;
			}
			set
			{
				if ((this._Langid != value))
				{
					this.OnLangidChanging(value);
					this.SendPropertyChanging();
					this._Langid = value;
					this.SendPropertyChanged("Langid");
					this.OnLangidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this.OnUpdatedChanging(value);
					this.SendPropertyChanging();
					this._Updated = value;
					this.SendPropertyChanged("Updated");
					this.OnUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelName", DbType="NVarChar(450)")]
		public string ModelName
		{
			get
			{
				return this._ModelName;
			}
			set
			{
				if ((this._ModelName != value))
				{
					this.OnModelNameChanging(value);
					this.SendPropertyChanging();
					this._ModelName = value;
					this.SendPropertyChanged("ModelName");
					this.OnModelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Supplier_id
		{
			get
			{
				return this._Supplier_id;
			}
			set
			{
				if ((this._Supplier_id != value))
				{
					this.OnSupplier_idChanging(value);
					this.SendPropertyChanging();
					this._Supplier_id = value;
					this.SendPropertyChanged("Supplier_id");
					this.OnSupplier_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_ProductDescription")]
	public partial class dt_ProductDescription : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Product_ID;
		
		private System.Nullable<double> _ProductDescription_ID;
		
		private string _URL;
		
		private int _langid;
		
		private string _PDFURL;
		
		private string _ShortDesc;
		
		private string _LongDesc;
		
		private string _WarrantyInfo;
		
		private System.Nullable<double> _PDFSize;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduct_IDChanging(int value);
    partial void OnProduct_IDChanged();
    partial void OnProductDescription_IDChanging(System.Nullable<double> value);
    partial void OnProductDescription_IDChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnlangidChanging(int value);
    partial void OnlangidChanged();
    partial void OnPDFURLChanging(string value);
    partial void OnPDFURLChanged();
    partial void OnShortDescChanging(string value);
    partial void OnShortDescChanged();
    partial void OnLongDescChanging(string value);
    partial void OnLongDescChanged();
    partial void OnWarrantyInfoChanging(string value);
    partial void OnWarrantyInfoChanged();
    partial void OnPDFSizeChanging(System.Nullable<double> value);
    partial void OnPDFSizeChanged();
    #endregion
		
		public dt_ProductDescription()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this.OnProduct_IDChanging(value);
					this.SendPropertyChanging();
					this._Product_ID = value;
					this.SendPropertyChanged("Product_ID");
					this.OnProduct_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDescription_ID", DbType="Float")]
		public System.Nullable<double> ProductDescription_ID
		{
			get
			{
				return this._ProductDescription_ID;
			}
			set
			{
				if ((this._ProductDescription_ID != value))
				{
					this.OnProductDescription_IDChanging(value);
					this.SendPropertyChanging();
					this._ProductDescription_ID = value;
					this.SendPropertyChanged("ProductDescription_ID");
					this.OnProductDescription_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(500)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_langid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int langid
		{
			get
			{
				return this._langid;
			}
			set
			{
				if ((this._langid != value))
				{
					this.OnlangidChanging(value);
					this.SendPropertyChanging();
					this._langid = value;
					this.SendPropertyChanged("langid");
					this.OnlangidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFURL", DbType="NVarChar(250)")]
		public string PDFURL
		{
			get
			{
				return this._PDFURL;
			}
			set
			{
				if ((this._PDFURL != value))
				{
					this.OnPDFURLChanging(value);
					this.SendPropertyChanging();
					this._PDFURL = value;
					this.SendPropertyChanged("PDFURL");
					this.OnPDFURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDesc", DbType="NVarChar(750)")]
		public string ShortDesc
		{
			get
			{
				return this._ShortDesc;
			}
			set
			{
				if ((this._ShortDesc != value))
				{
					this.OnShortDescChanging(value);
					this.SendPropertyChanging();
					this._ShortDesc = value;
					this.SendPropertyChanged("ShortDesc");
					this.OnShortDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongDesc", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LongDesc
		{
			get
			{
				return this._LongDesc;
			}
			set
			{
				if ((this._LongDesc != value))
				{
					this.OnLongDescChanging(value);
					this.SendPropertyChanging();
					this._LongDesc = value;
					this.SendPropertyChanged("LongDesc");
					this.OnLongDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarrantyInfo", DbType="NVarChar(2500)")]
		public string WarrantyInfo
		{
			get
			{
				return this._WarrantyInfo;
			}
			set
			{
				if ((this._WarrantyInfo != value))
				{
					this.OnWarrantyInfoChanging(value);
					this.SendPropertyChanging();
					this._WarrantyInfo = value;
					this.SendPropertyChanged("WarrantyInfo");
					this.OnWarrantyInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFSize", DbType="Float")]
		public System.Nullable<double> PDFSize
		{
			get
			{
				return this._PDFSize;
			}
			set
			{
				if ((this._PDFSize != value))
				{
					this.OnPDFSizeChanging(value);
					this.SendPropertyChanging();
					this._PDFSize = value;
					this.SendPropertyChanged("PDFSize");
					this.OnPDFSizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dt_ProductRelated")]
	public partial class dt_ProductRelated : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _Product_ID;
		
		private double _ProductRelated_ID;
		
		private double _Category_ID;
		
		private string _Reversed;
		
		private string _Preferred;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduct_IDChanging(double value);
    partial void OnProduct_IDChanged();
    partial void OnProductRelated_IDChanging(double value);
    partial void OnProductRelated_IDChanged();
    partial void OnCategory_IDChanging(double value);
    partial void OnCategory_IDChanged();
    partial void OnReversedChanging(string value);
    partial void OnReversedChanged();
    partial void OnPreferredChanging(string value);
    partial void OnPreferredChanged();
    #endregion
		
		public dt_ProductRelated()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this.OnProduct_IDChanging(value);
					this.SendPropertyChanging();
					this._Product_ID = value;
					this.SendPropertyChanged("Product_ID");
					this.OnProduct_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductRelated_ID", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double ProductRelated_ID
		{
			get
			{
				return this._ProductRelated_ID;
			}
			set
			{
				if ((this._ProductRelated_ID != value))
				{
					this.OnProductRelated_IDChanging(value);
					this.SendPropertyChanging();
					this._ProductRelated_ID = value;
					this.SendPropertyChanged("ProductRelated_ID");
					this.OnProductRelated_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_ID", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double Category_ID
		{
			get
			{
				return this._Category_ID;
			}
			set
			{
				if ((this._Category_ID != value))
				{
					this.OnCategory_IDChanging(value);
					this.SendPropertyChanging();
					this._Category_ID = value;
					this.SendPropertyChanged("Category_ID");
					this.OnCategory_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reversed", DbType="NVarChar(50)")]
		public string Reversed
		{
			get
			{
				return this._Reversed;
			}
			set
			{
				if ((this._Reversed != value))
				{
					this.OnReversedChanging(value);
					this.SendPropertyChanging();
					this._Reversed = value;
					this.SendPropertyChanged("Reversed");
					this.OnReversedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preferred", DbType="NVarChar(50)")]
		public string Preferred
		{
			get
			{
				return this._Preferred;
			}
			set
			{
				if ((this._Preferred != value))
				{
					this.OnPreferredChanging(value);
					this.SendPropertyChanging();
					this._Preferred = value;
					this.SendPropertyChanged("Preferred");
					this.OnPreferredChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Concentrator_GetIceProductAttributebyManufactIDResult
	{
		
		private int _Product_ID;
		
		private double _Feature_ID;
		
		private string _AttributeName;
		
		private string _Value;
		
		private string _Sign;
		
		private System.Nullable<int> _FeatureIndex;
		
		private System.Nullable<int> _IsSearchable;
		
		private System.Nullable<int> _KeyFeature;
		
		private System.Nullable<int> _AttributeGroupID;
		
		private string _AttributeGroupName;
		
		private System.Nullable<int> _AttributeGroupIndex;
		
		private string _LanguageSign;
		
		public Concentrator_GetIceProductAttributebyManufactIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Int NOT NULL")]
		public int Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this._Product_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Feature_ID", DbType="Float NOT NULL")]
		public double Feature_ID
		{
			get
			{
				return this._Feature_ID;
			}
			set
			{
				if ((this._Feature_ID != value))
				{
					this._Feature_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeName", DbType="NVarChar(150)")]
		public string AttributeName
		{
			get
			{
				return this._AttributeName;
			}
			set
			{
				if ((this._AttributeName != value))
				{
					this._AttributeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="VarChar(6000)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sign", DbType="NVarChar(50)")]
		public string Sign
		{
			get
			{
				return this._Sign;
			}
			set
			{
				if ((this._Sign != value))
				{
					this._Sign = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeatureIndex", DbType="Int")]
		public System.Nullable<int> FeatureIndex
		{
			get
			{
				return this._FeatureIndex;
			}
			set
			{
				if ((this._FeatureIndex != value))
				{
					this._FeatureIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSearchable", DbType="Int")]
		public System.Nullable<int> IsSearchable
		{
			get
			{
				return this._IsSearchable;
			}
			set
			{
				if ((this._IsSearchable != value))
				{
					this._IsSearchable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyFeature", DbType="Int")]
		public System.Nullable<int> KeyFeature
		{
			get
			{
				return this._KeyFeature;
			}
			set
			{
				if ((this._KeyFeature != value))
				{
					this._KeyFeature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeGroupID", DbType="Int")]
		public System.Nullable<int> AttributeGroupID
		{
			get
			{
				return this._AttributeGroupID;
			}
			set
			{
				if ((this._AttributeGroupID != value))
				{
					this._AttributeGroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeGroupName", DbType="NVarChar(300)")]
		public string AttributeGroupName
		{
			get
			{
				return this._AttributeGroupName;
			}
			set
			{
				if ((this._AttributeGroupName != value))
				{
					this._AttributeGroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeGroupIndex", DbType="Int")]
		public System.Nullable<int> AttributeGroupIndex
		{
			get
			{
				return this._AttributeGroupIndex;
			}
			set
			{
				if ((this._AttributeGroupIndex != value))
				{
					this._AttributeGroupIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageSign", DbType="NChar(10)")]
		public string LanguageSign
		{
			get
			{
				return this._LanguageSign;
			}
			set
			{
				if ((this._LanguageSign != value))
				{
					this._LanguageSign = value;
				}
			}
		}
	}
	
	public partial class Concentrator_GetIceProductAttributesResult
	{
		
		private int _Product_ID;
		
		private double _Feature_ID;
		
		private string _AttributeName;
		
		private string _Value;
		
		private string _Sign;
		
		private System.Nullable<int> _FeatureIndex;
		
		private System.Nullable<int> _IsSearchable;
		
		private System.Nullable<int> _KeyFeature;
		
		private System.Nullable<int> _AttributeGroupID;
		
		private string _AttributeGroupName;
		
		private System.Nullable<int> _AttributeGroupIndex;
		
		private string _LanguageSign;
		
		private string _ManufacturerID;
		
		private int _SupplierID;
		
		public Concentrator_GetIceProductAttributesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Int NOT NULL")]
		public int Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this._Product_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Feature_ID", DbType="Float NOT NULL")]
		public double Feature_ID
		{
			get
			{
				return this._Feature_ID;
			}
			set
			{
				if ((this._Feature_ID != value))
				{
					this._Feature_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeName", DbType="NVarChar(150)")]
		public string AttributeName
		{
			get
			{
				return this._AttributeName;
			}
			set
			{
				if ((this._AttributeName != value))
				{
					this._AttributeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="VarChar(6000)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sign", DbType="NVarChar(50)")]
		public string Sign
		{
			get
			{
				return this._Sign;
			}
			set
			{
				if ((this._Sign != value))
				{
					this._Sign = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeatureIndex", DbType="Int")]
		public System.Nullable<int> FeatureIndex
		{
			get
			{
				return this._FeatureIndex;
			}
			set
			{
				if ((this._FeatureIndex != value))
				{
					this._FeatureIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSearchable", DbType="Int")]
		public System.Nullable<int> IsSearchable
		{
			get
			{
				return this._IsSearchable;
			}
			set
			{
				if ((this._IsSearchable != value))
				{
					this._IsSearchable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyFeature", DbType="Int")]
		public System.Nullable<int> KeyFeature
		{
			get
			{
				return this._KeyFeature;
			}
			set
			{
				if ((this._KeyFeature != value))
				{
					this._KeyFeature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeGroupID", DbType="Int")]
		public System.Nullable<int> AttributeGroupID
		{
			get
			{
				return this._AttributeGroupID;
			}
			set
			{
				if ((this._AttributeGroupID != value))
				{
					this._AttributeGroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeGroupName", DbType="NVarChar(300)")]
		public string AttributeGroupName
		{
			get
			{
				return this._AttributeGroupName;
			}
			set
			{
				if ((this._AttributeGroupName != value))
				{
					this._AttributeGroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeGroupIndex", DbType="Int")]
		public System.Nullable<int> AttributeGroupIndex
		{
			get
			{
				return this._AttributeGroupIndex;
			}
			set
			{
				if ((this._AttributeGroupIndex != value))
				{
					this._AttributeGroupIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageSign", DbType="NVarChar(50)")]
		public string LanguageSign
		{
			get
			{
				return this._LanguageSign;
			}
			set
			{
				if ((this._LanguageSign != value))
				{
					this._LanguageSign = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManufacturerID", DbType="NVarChar(75)")]
		public string ManufacturerID
		{
			get
			{
				return this._ManufacturerID;
			}
			set
			{
				if ((this._ManufacturerID != value))
				{
					this._ManufacturerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierID", DbType="Int NOT NULL")]
		public int SupplierID
		{
			get
			{
				return this._SupplierID;
			}
			set
			{
				if ((this._SupplierID != value))
				{
					this._SupplierID = value;
				}
			}
		}
	}
	
	public partial class Concentrator_GetIceCatAttributeResult
	{
		
		private System.Nullable<int> _AttributeGroupID;
		
		private string _AttributeGroupName;
		
		private System.Nullable<int> _AttributeGroupIndex;
		
		private int _Product_ID;
		
		private double _Feature_ID;
		
		private string _AttributeName;
		
		private string _Value;
		
		private string _Sign;
		
		private System.Nullable<int> _FeatureIndex;
		
		private System.Nullable<int> _IsSearchable;
		
		private string _Presentation_Value;
		
		public Concentrator_GetIceCatAttributeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeGroupID", DbType="Int")]
		public System.Nullable<int> AttributeGroupID
		{
			get
			{
				return this._AttributeGroupID;
			}
			set
			{
				if ((this._AttributeGroupID != value))
				{
					this._AttributeGroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeGroupName", DbType="NVarChar(300)")]
		public string AttributeGroupName
		{
			get
			{
				return this._AttributeGroupName;
			}
			set
			{
				if ((this._AttributeGroupName != value))
				{
					this._AttributeGroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeGroupIndex", DbType="Int")]
		public System.Nullable<int> AttributeGroupIndex
		{
			get
			{
				return this._AttributeGroupIndex;
			}
			set
			{
				if ((this._AttributeGroupIndex != value))
				{
					this._AttributeGroupIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Int NOT NULL")]
		public int Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this._Product_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Feature_ID", DbType="Float NOT NULL")]
		public double Feature_ID
		{
			get
			{
				return this._Feature_ID;
			}
			set
			{
				if ((this._Feature_ID != value))
				{
					this._Feature_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeName", DbType="NVarChar(150)")]
		public string AttributeName
		{
			get
			{
				return this._AttributeName;
			}
			set
			{
				if ((this._AttributeName != value))
				{
					this._AttributeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="VarChar(6000)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sign", DbType="NVarChar(50)")]
		public string Sign
		{
			get
			{
				return this._Sign;
			}
			set
			{
				if ((this._Sign != value))
				{
					this._Sign = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeatureIndex", DbType="Int")]
		public System.Nullable<int> FeatureIndex
		{
			get
			{
				return this._FeatureIndex;
			}
			set
			{
				if ((this._FeatureIndex != value))
				{
					this._FeatureIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSearchable", DbType="Int")]
		public System.Nullable<int> IsSearchable
		{
			get
			{
				return this._IsSearchable;
			}
			set
			{
				if ((this._IsSearchable != value))
				{
					this._IsSearchable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Presentation_Value", DbType="VarChar(7000)")]
		public string Presentation_Value
		{
			get
			{
				return this._Presentation_Value;
			}
			set
			{
				if ((this._Presentation_Value != value))
				{
					this._Presentation_Value = value;
				}
			}
		}
	}
	
	public partial class Concentrator_GetIceProductbyManufactIDResult
	{
		
		private int _Product_ID;
		
		private System.Nullable<double> _ThumbPicSize;
		
		private string _Quality;
		
		private string _HighPic;
		
		private string _LowPic;
		
		private System.Nullable<double> _LowPicSize;
		
		private string _Prod_ID;
		
		private System.Nullable<double> _HighPicSize;
		
		private string _ThumbPic;
		
		private string _Code;
		
		private string _Name;
		
		private string _Langid;
		
		private string _Updated;
		
		private string _ModelName;
		
		private int _Supplier_id;
		
		private System.Nullable<int> _Product_ID1;
		
		private System.Nullable<double> _ProductDescription_ID;
		
		private string _URL;
		
		private System.Nullable<int> _langid1;
		
		private string _PDFURL;
		
		private string _ShortDesc;
		
		private string _LongDesc;
		
		private string _WarrantyInfo;
		
		private System.Nullable<double> _PDFSize;
		
		private System.Nullable<int> _Product_ID2;
		
		private System.Nullable<double> _Supplier_ID1;
		
		private string _Supplier_Name;
		
		public Concentrator_GetIceProductbyManufactIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Int NOT NULL")]
		public int Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this._Product_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbPicSize", DbType="Float")]
		public System.Nullable<double> ThumbPicSize
		{
			get
			{
				return this._ThumbPicSize;
			}
			set
			{
				if ((this._ThumbPicSize != value))
				{
					this._ThumbPicSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quality", DbType="NVarChar(50)")]
		public string Quality
		{
			get
			{
				return this._Quality;
			}
			set
			{
				if ((this._Quality != value))
				{
					this._Quality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighPic", DbType="NVarChar(100)")]
		public string HighPic
		{
			get
			{
				return this._HighPic;
			}
			set
			{
				if ((this._HighPic != value))
				{
					this._HighPic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPic", DbType="NVarChar(100)")]
		public string LowPic
		{
			get
			{
				return this._LowPic;
			}
			set
			{
				if ((this._LowPic != value))
				{
					this._LowPic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPicSize", DbType="Float")]
		public System.Nullable<double> LowPicSize
		{
			get
			{
				return this._LowPicSize;
			}
			set
			{
				if ((this._LowPicSize != value))
				{
					this._LowPicSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_ID", DbType="NVarChar(75)")]
		public string Prod_ID
		{
			get
			{
				return this._Prod_ID;
			}
			set
			{
				if ((this._Prod_ID != value))
				{
					this._Prod_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighPicSize", DbType="Float")]
		public System.Nullable<double> HighPicSize
		{
			get
			{
				return this._HighPicSize;
			}
			set
			{
				if ((this._HighPicSize != value))
				{
					this._HighPicSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbPic", DbType="NVarChar(75)")]
		public string ThumbPic
		{
			get
			{
				return this._ThumbPic;
			}
			set
			{
				if ((this._ThumbPic != value))
				{
					this._ThumbPic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(175)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Langid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Langid
		{
			get
			{
				return this._Langid;
			}
			set
			{
				if ((this._Langid != value))
				{
					this._Langid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelName", DbType="NVarChar(450)")]
		public string ModelName
		{
			get
			{
				return this._ModelName;
			}
			set
			{
				if ((this._ModelName != value))
				{
					this._ModelName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_id", DbType="Int NOT NULL")]
		public int Supplier_id
		{
			get
			{
				return this._Supplier_id;
			}
			set
			{
				if ((this._Supplier_id != value))
				{
					this._Supplier_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID1", DbType="Int")]
		public System.Nullable<int> Product_ID1
		{
			get
			{
				return this._Product_ID1;
			}
			set
			{
				if ((this._Product_ID1 != value))
				{
					this._Product_ID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDescription_ID", DbType="Float")]
		public System.Nullable<double> ProductDescription_ID
		{
			get
			{
				return this._ProductDescription_ID;
			}
			set
			{
				if ((this._ProductDescription_ID != value))
				{
					this._ProductDescription_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(500)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_langid1", DbType="Int")]
		public System.Nullable<int> langid1
		{
			get
			{
				return this._langid1;
			}
			set
			{
				if ((this._langid1 != value))
				{
					this._langid1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFURL", DbType="NVarChar(250)")]
		public string PDFURL
		{
			get
			{
				return this._PDFURL;
			}
			set
			{
				if ((this._PDFURL != value))
				{
					this._PDFURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDesc", DbType="NVarChar(750)")]
		public string ShortDesc
		{
			get
			{
				return this._ShortDesc;
			}
			set
			{
				if ((this._ShortDesc != value))
				{
					this._ShortDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongDesc", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LongDesc
		{
			get
			{
				return this._LongDesc;
			}
			set
			{
				if ((this._LongDesc != value))
				{
					this._LongDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarrantyInfo", DbType="NVarChar(2500)")]
		public string WarrantyInfo
		{
			get
			{
				return this._WarrantyInfo;
			}
			set
			{
				if ((this._WarrantyInfo != value))
				{
					this._WarrantyInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFSize", DbType="Float")]
		public System.Nullable<double> PDFSize
		{
			get
			{
				return this._PDFSize;
			}
			set
			{
				if ((this._PDFSize != value))
				{
					this._PDFSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID2", DbType="Int")]
		public System.Nullable<int> Product_ID2
		{
			get
			{
				return this._Product_ID2;
			}
			set
			{
				if ((this._Product_ID2 != value))
				{
					this._Product_ID2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_ID1", DbType="Float")]
		public System.Nullable<double> Supplier_ID1
		{
			get
			{
				return this._Supplier_ID1;
			}
			set
			{
				if ((this._Supplier_ID1 != value))
				{
					this._Supplier_ID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_Name", DbType="NVarChar(50)")]
		public string Supplier_Name
		{
			get
			{
				return this._Supplier_Name;
			}
			set
			{
				if ((this._Supplier_Name != value))
				{
					this._Supplier_Name = value;
				}
			}
		}
	}
	
	public partial class Concentrator_GetIceProductFullbyManufactIDResult
	{
		
		private int _Product_ID;
		
		private System.Nullable<double> _ThumbPicSize;
		
		private string _Quality;
		
		private string _HighPic;
		
		private string _LowPic;
		
		private System.Nullable<double> _LowPicSize;
		
		private string _Prod_ID;
		
		private System.Nullable<double> _HighPicSize;
		
		private string _ThumbPic;
		
		private string _Code;
		
		private string _Name;
		
		private string _Langid;
		
		private string _Updated;
		
		private string _ModelName;
		
		private int _Supplier_id;
		
		private System.Nullable<int> _Product_ID1;
		
		private System.Nullable<double> _ProductDescription_ID;
		
		private string _URL;
		
		private System.Nullable<int> _langid1;
		
		private string _PDFURL;
		
		private string _ShortDesc;
		
		private string _LongDesc;
		
		private string _WarrantyInfo;
		
		private System.Nullable<double> _PDFSize;
		
		private System.Nullable<int> _Product_ID2;
		
		private System.Nullable<double> _Supplier_ID1;
		
		private string _Supplier_Name;
		
		public Concentrator_GetIceProductFullbyManufactIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Int NOT NULL")]
		public int Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this._Product_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbPicSize", DbType="Float")]
		public System.Nullable<double> ThumbPicSize
		{
			get
			{
				return this._ThumbPicSize;
			}
			set
			{
				if ((this._ThumbPicSize != value))
				{
					this._ThumbPicSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quality", DbType="NVarChar(50)")]
		public string Quality
		{
			get
			{
				return this._Quality;
			}
			set
			{
				if ((this._Quality != value))
				{
					this._Quality = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighPic", DbType="NVarChar(100)")]
		public string HighPic
		{
			get
			{
				return this._HighPic;
			}
			set
			{
				if ((this._HighPic != value))
				{
					this._HighPic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPic", DbType="NVarChar(100)")]
		public string LowPic
		{
			get
			{
				return this._LowPic;
			}
			set
			{
				if ((this._LowPic != value))
				{
					this._LowPic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPicSize", DbType="Float")]
		public System.Nullable<double> LowPicSize
		{
			get
			{
				return this._LowPicSize;
			}
			set
			{
				if ((this._LowPicSize != value))
				{
					this._LowPicSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_ID", DbType="NVarChar(75)")]
		public string Prod_ID
		{
			get
			{
				return this._Prod_ID;
			}
			set
			{
				if ((this._Prod_ID != value))
				{
					this._Prod_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighPicSize", DbType="Float")]
		public System.Nullable<double> HighPicSize
		{
			get
			{
				return this._HighPicSize;
			}
			set
			{
				if ((this._HighPicSize != value))
				{
					this._HighPicSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThumbPic", DbType="NVarChar(75)")]
		public string ThumbPic
		{
			get
			{
				return this._ThumbPic;
			}
			set
			{
				if ((this._ThumbPic != value))
				{
					this._ThumbPic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(175)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Langid", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Langid
		{
			get
			{
				return this._Langid;
			}
			set
			{
				if ((this._Langid != value))
				{
					this._Langid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this._Updated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelName", DbType="NVarChar(450)")]
		public string ModelName
		{
			get
			{
				return this._ModelName;
			}
			set
			{
				if ((this._ModelName != value))
				{
					this._ModelName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_id", DbType="Int NOT NULL")]
		public int Supplier_id
		{
			get
			{
				return this._Supplier_id;
			}
			set
			{
				if ((this._Supplier_id != value))
				{
					this._Supplier_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID1", DbType="Int")]
		public System.Nullable<int> Product_ID1
		{
			get
			{
				return this._Product_ID1;
			}
			set
			{
				if ((this._Product_ID1 != value))
				{
					this._Product_ID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDescription_ID", DbType="Float")]
		public System.Nullable<double> ProductDescription_ID
		{
			get
			{
				return this._ProductDescription_ID;
			}
			set
			{
				if ((this._ProductDescription_ID != value))
				{
					this._ProductDescription_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(500)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_langid1", DbType="Int")]
		public System.Nullable<int> langid1
		{
			get
			{
				return this._langid1;
			}
			set
			{
				if ((this._langid1 != value))
				{
					this._langid1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFURL", DbType="NVarChar(250)")]
		public string PDFURL
		{
			get
			{
				return this._PDFURL;
			}
			set
			{
				if ((this._PDFURL != value))
				{
					this._PDFURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDesc", DbType="NVarChar(750)")]
		public string ShortDesc
		{
			get
			{
				return this._ShortDesc;
			}
			set
			{
				if ((this._ShortDesc != value))
				{
					this._ShortDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongDesc", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LongDesc
		{
			get
			{
				return this._LongDesc;
			}
			set
			{
				if ((this._LongDesc != value))
				{
					this._LongDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarrantyInfo", DbType="NVarChar(2500)")]
		public string WarrantyInfo
		{
			get
			{
				return this._WarrantyInfo;
			}
			set
			{
				if ((this._WarrantyInfo != value))
				{
					this._WarrantyInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFSize", DbType="Float")]
		public System.Nullable<double> PDFSize
		{
			get
			{
				return this._PDFSize;
			}
			set
			{
				if ((this._PDFSize != value))
				{
					this._PDFSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID2", DbType="Int")]
		public System.Nullable<int> Product_ID2
		{
			get
			{
				return this._Product_ID2;
			}
			set
			{
				if ((this._Product_ID2 != value))
				{
					this._Product_ID2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_ID1", DbType="Float")]
		public System.Nullable<double> Supplier_ID1
		{
			get
			{
				return this._Supplier_ID1;
			}
			set
			{
				if ((this._Supplier_ID1 != value))
				{
					this._Supplier_ID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_Name", DbType="NVarChar(50)")]
		public string Supplier_Name
		{
			get
			{
				return this._Supplier_Name;
			}
			set
			{
				if ((this._Supplier_Name != value))
				{
					this._Supplier_Name = value;
				}
			}
		}
	}
	
	public partial class Concentrator_GetIceProductCategoriesResult
	{
		
		private string _Prod_ID;
		
		private System.Nullable<int> _Cat_ID;
		
		private System.Nullable<int> _Supplier_id;
		
		public Concentrator_GetIceProductCategoriesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prod_ID", DbType="NVarChar(250)")]
		public string Prod_ID
		{
			get
			{
				return this._Prod_ID;
			}
			set
			{
				if ((this._Prod_ID != value))
				{
					this._Prod_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_ID", DbType="Int")]
		public System.Nullable<int> Cat_ID
		{
			get
			{
				return this._Cat_ID;
			}
			set
			{
				if ((this._Cat_ID != value))
				{
					this._Cat_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supplier_id", DbType="Int")]
		public System.Nullable<int> Supplier_id
		{
			get
			{
				return this._Supplier_id;
			}
			set
			{
				if ((this._Supplier_id != value))
				{
					this._Supplier_id = value;
				}
			}
		}
	}
	
	public partial class Concentrator_GetIceCategoryResult
	{
		
		private System.Nullable<int> _Cat_ID;
		
		private string _Name_ID;
		
		private string _langid;
		
		private string _CategoryName;
		
		private System.Nullable<int> _Parent_Cat_ID;
		
		private string _Parent_CategoryName;
		
		private string _Parent_NameID;
		
		public Concentrator_GetIceCategoryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat_ID", DbType="Int")]
		public System.Nullable<int> Cat_ID
		{
			get
			{
				return this._Cat_ID;
			}
			set
			{
				if ((this._Cat_ID != value))
				{
					this._Cat_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_ID", DbType="NVarChar(53)")]
		public string Name_ID
		{
			get
			{
				return this._Name_ID;
			}
			set
			{
				if ((this._Name_ID != value))
				{
					this._Name_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_langid", DbType="NVarChar(50)")]
		public string langid
		{
			get
			{
				return this._langid;
			}
			set
			{
				if ((this._langid != value))
				{
					this._langid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(1500)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_Cat_ID", DbType="Int")]
		public System.Nullable<int> Parent_Cat_ID
		{
			get
			{
				return this._Parent_Cat_ID;
			}
			set
			{
				if ((this._Parent_Cat_ID != value))
				{
					this._Parent_Cat_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_CategoryName", DbType="NVarChar(1500)")]
		public string Parent_CategoryName
		{
			get
			{
				return this._Parent_CategoryName;
			}
			set
			{
				if ((this._Parent_CategoryName != value))
				{
					this._Parent_CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent_NameID", DbType="NVarChar(53)")]
		public string Parent_NameID
		{
			get
			{
				return this._Parent_NameID;
			}
			set
			{
				if ((this._Parent_NameID != value))
				{
					this._Parent_NameID = value;
				}
			}
		}
	}
	
	public partial class Concentrator_GetIceProductDescriptionsResult
	{
		
		private int _SupplierID;
		
		private string _VendorItemNumber;
		
		private string _ShortDescription;
		
		private string _LongDescription;
		
		private int _LanguageID;
		
		private string _PDFUrl;
		
		private System.Nullable<double> _PDFSize;
		
		private string _Url;
		
		private string _WarrentyInfo;
		
		private string _LongSummaryDescription;
		
		private string _ShortSummaryDescription;
		
		private string _ModelName;
		
		private string _Name;
		
		private string _Quality;
		
		public Concentrator_GetIceProductDescriptionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierID", DbType="Int NOT NULL")]
		public int SupplierID
		{
			get
			{
				return this._SupplierID;
			}
			set
			{
				if ((this._SupplierID != value))
				{
					this._SupplierID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorItemNumber", DbType="NVarChar(75)")]
		public string VendorItemNumber
		{
			get
			{
				return this._VendorItemNumber;
			}
			set
			{
				if ((this._VendorItemNumber != value))
				{
					this._VendorItemNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDescription", DbType="NVarChar(750)")]
		public string ShortDescription
		{
			get
			{
				return this._ShortDescription;
			}
			set
			{
				if ((this._ShortDescription != value))
				{
					this._ShortDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongDescription", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LongDescription
		{
			get
			{
				return this._LongDescription;
			}
			set
			{
				if ((this._LongDescription != value))
				{
					this._LongDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageID", DbType="Int NOT NULL")]
		public int LanguageID
		{
			get
			{
				return this._LanguageID;
			}
			set
			{
				if ((this._LanguageID != value))
				{
					this._LanguageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFUrl", DbType="NVarChar(250)")]
		public string PDFUrl
		{
			get
			{
				return this._PDFUrl;
			}
			set
			{
				if ((this._PDFUrl != value))
				{
					this._PDFUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFSize", DbType="Float")]
		public System.Nullable<double> PDFSize
		{
			get
			{
				return this._PDFSize;
			}
			set
			{
				if ((this._PDFSize != value))
				{
					this._PDFSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(500)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarrentyInfo", DbType="NVarChar(2500)")]
		public string WarrentyInfo
		{
			get
			{
				return this._WarrentyInfo;
			}
			set
			{
				if ((this._WarrentyInfo != value))
				{
					this._WarrentyInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongSummaryDescription", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string LongSummaryDescription
		{
			get
			{
				return this._LongSummaryDescription;
			}
			set
			{
				if ((this._LongSummaryDescription != value))
				{
					this._LongSummaryDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortSummaryDescription", DbType="NVarChar(750)")]
		public string ShortSummaryDescription
		{
			get
			{
				return this._ShortSummaryDescription;
			}
			set
			{
				if ((this._ShortSummaryDescription != value))
				{
					this._ShortSummaryDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelName", DbType="NVarChar(450)")]
		public string ModelName
		{
			get
			{
				return this._ModelName;
			}
			set
			{
				if ((this._ModelName != value))
				{
					this._ModelName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(175)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quality", DbType="NVarChar(50)")]
		public string Quality
		{
			get
			{
				return this._Quality;
			}
			set
			{
				if ((this._Quality != value))
				{
					this._Quality = value;
				}
			}
		}
	}
	
	public partial class Concentrator_GetIceProductImageUrlbyICEcatIDResult
	{
		
		private string _Picture;
		
		private int _BaseImage;
		
		public Concentrator_GetIceProductImageUrlbyICEcatIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(255)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this._Picture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseImage", DbType="Int NOT NULL")]
		public int BaseImage
		{
			get
			{
				return this._BaseImage;
			}
			set
			{
				if ((this._BaseImage != value))
				{
					this._BaseImage = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
