//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concentrator.Plugins.BAS.WebExport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=generaldb;Initial Catalog=BasWeb_Staging;Persist Security Info=True;U" +
            "ser ID=BasWeb_Staging_AppUser;Password=?+0m!Z2x")]
        public string BasWeb_StagingConnectionString {
            get {
                return ((string)(this["BasWeb_StagingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.0.77;Initial Catalog=Bram_Dev_Test;User ID=replication;Passwor" +
            "d=oct0pu$$y")]
        public string Bram_Dev_TestConnectionString {
            get {
                return ((string)(this["Bram_Dev_TestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.0.77;Initial Catalog=Bram_Dev_Test;User ID=replication;Passwor" +
            "d=oct0pu$$y")]
        public string Bram_Dev_TestConnectionString1 {
            get {
                return ((string)(this["Bram_Dev_TestConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.0.77;Initial Catalog=Bram_Dev_Test;User ID=replication")]
        public string Bram_Dev_TestConnectionString2 {
            get {
                return ((string)(this["Bram_Dev_TestConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mercurius;Initial Catalog=MyCom_Shop_Content;Persist Security Info=Tr" +
            "ue;User ID=spider")]
        public string MyCom_Shop_ContentConnectionString {
            get {
                return ((string)(this["MyCom_Shop_ContentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.94.190;Initial Catalog=MyComWEBV2_Prod;Persist Security Info=" +
            "True;User ID=bram_portal;Password=bram")]
        public string MyComWEBV2_ProdConnectionString {
            get {
                return ((string)(this["MyComWEBV2_ProdConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.94.189;Initial Catalog=MyComWEB_Staging;Persist Security Info" +
            "=True;User ID=bram_portal;Password=bram")]
        public string MyComWEB_StagingConnectionString {
            get {
                return ((string)(this["MyComWEB_StagingConnectionString"]));
            }
        }
    }
}
