//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concentrator.Web.ServiceClient.JdeCustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JdeCustomerService.JDECustomerSoap")]
    public interface JDECustomerSoap {
        
        // CODEGEN: Generating message contract since element name BusinessUnit from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerData", ReplyAction="*")]
        Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataResponse GetCustomerData(Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerData", Namespace="http://tempuri.org/", Order=0)]
        public Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataRequestBody Body;
        
        public GetCustomerDataRequest() {
        }
        
        public GetCustomerDataRequest(Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BusinessUnit;
        
        public GetCustomerDataRequestBody() {
        }
        
        public GetCustomerDataRequestBody(string BusinessUnit) {
            this.BusinessUnit = BusinessUnit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataResponseBody Body;
        
        public GetCustomerDataResponse() {
        }
        
        public GetCustomerDataResponse(Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCustomerDataResult;
        
        public GetCustomerDataResponseBody() {
        }
        
        public GetCustomerDataResponseBody(string GetCustomerDataResult) {
            this.GetCustomerDataResult = GetCustomerDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JDECustomerSoapChannel : Concentrator.Web.ServiceClient.JdeCustomerService.JDECustomerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JDECustomerSoapClient : System.ServiceModel.ClientBase<Concentrator.Web.ServiceClient.JdeCustomerService.JDECustomerSoap>, Concentrator.Web.ServiceClient.JdeCustomerService.JDECustomerSoap {
        
        public JDECustomerSoapClient() {
        }
        
        public JDECustomerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JDECustomerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JDECustomerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JDECustomerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataResponse Concentrator.Web.ServiceClient.JdeCustomerService.JDECustomerSoap.GetCustomerData(Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataRequest request) {
            return base.Channel.GetCustomerData(request);
        }
        
        public string GetCustomerData(string BusinessUnit) {
            Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataRequest inValue = new Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataRequest();
            inValue.Body = new Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataRequestBody();
            inValue.Body.BusinessUnit = BusinessUnit;
            Concentrator.Web.ServiceClient.JdeCustomerService.GetCustomerDataResponse retVal = ((Concentrator.Web.ServiceClient.JdeCustomerService.JDECustomerSoap)(this)).GetCustomerData(inValue);
            return retVal.Body.GetCustomerDataResult;
        }
    }
}
